### ISSUE TITLE
Deploy multicall3 to Cronos Testnet

### ISSUE THREAD

**Issue by 0xartcro** [mds1/multicall#100]
### Chain Name

Cronos Testnet

### Chain ID

338

### RPC URL

https://evm-t3.cronos.org

### Block Explorer URL

https://cronos.org/explorer/testnet3

### Deployment Funds

Yes

**Comment by 0xartcro** [comment]
I've sent 30 tCRO there. Hopefully will be enough

**Comment by mds1** [comment]
Done, thanks!
