### ISSUE TITLE
Syscoin Rollux Mainnet

### ISSUE THREAD

**Issue by sidhujag** [mds1/multicall#101]
### Chain Name

Syscoin Rollux Mainnet (L2) (testnets + L1 here: https://github.com/mds1/multicall/issues/79)

### Chain ID

570

### RPC URL

https://rpc.rollux.com

### Block Explorer URL

https://explorer.rollux.com

### Deployment Funds

Yes

**Comment by mds1** [comment]
Done, thanks!
