### ISSUE TITLE
non-contract methods

### ISSUE THREAD

**Issue by fopina** [mds1/multicall#102]
Is it possible to use this for methods like get_balance(uint256 address)? (Meaning balance of chain token, not a smart contract)

**Comment by mds1** [comment]
Sorry can you clarify, I don't understand the question? You can use the multicall3 contract to call any on-chain method

**Comment by fopina** [comment]
I've been using multicall3 `aggregate` with `balanceOf` (ERC720) calls successfully.

But recently I wanted to also use it for regular chain token (`AVAX` token in the `Avalanche` chain, for instance) and I couldn't find a way to do so, as I don't have an "address". I suppose for encoding call data I can do it the same way as `balanceOf`, as method is the same

**Comment by mds1** [comment]
To get the balance of the chain's native token, use this method: https://github.com/mds1/multicall/blob/55c77eb39e2a5ca9e44153acda978b87647bd76c/src/Multicall3.sol#L194-L197

**Comment by fopina** [comment]
No idea how I missed that, worked perfectly, thanks!
