### ISSUE TITLE
EOS EVM Mainnet Deployment Request

### ISSUE THREAD

**Issue by DenisCarriere** [mds1/multicall#103]
### Chain Name

EOS EVM

### Chain ID

17777

### RPC URL

https://api.evm.eosnetwork.com

### Block Explorer URL

https://explorer.evm.eosnetwork.com

### Deployment Funds

Yes

**Comment by mds1** [comment]
Done, thanks!

**Comment by DenisCarriere** [comment]
@mds1 big thanks! 🙇
