### ISSUE TITLE
EOS EVM Testnet Deployment Request

### ISSUE THREAD

**Issue by DenisCarriere** [mds1/multicall#104]
### Chain Name

EOS EVM Testnet

### Chain ID

15557

### RPC URL

https://api.testnet.evm.eosnetwork.com

### Block Explorer URL

https://explorer.testnet.evm.eosnetwork.com

### Deployment Funds

Yes

**Comment by mds1** [comment]
Done, thanks!

**Comment by DenisCarriere** [comment]
Ref: Deployed on Block number [9067940](https://explorer.testnet.evm.eosnetwork.com/tx/0x8afa9da9752d0dcf1dbba47b345d0090eaaf27d3c4166d6b731de946a3d98f62)
