### ISSUE TITLE
Request Dogechain Multicall3 deployment

### ISSUE THREAD

**Issue by bigboydiamonds** [mds1/multicall#107]
### Chain Name

Dogechain

### Chain ID

2000

### RPC URL

https://rpc-us.dogechain.dog/

### Block Explorer URL

https://explorer.dogechain.dog/

### Deployment Funds

Yes

**Comment by Kaladin13** [comment]
Thanks for someone doing it! Multicall is very needed on dogechain indeed

**Comment by Hyperb0rean** [comment]
Big thanks! It is really needed!!

**Comment by Mopstream** [comment]
Very needed!!! Thanks!!!!!

**Comment by mds1** [comment]
Done, thanks!
