### ISSUE TITLE
Deploy Multicall3 to Arthera Testnet

### ISSUE THREAD

**Issue by julienbrg** [mds1/multicall#112]
### Chain Name

Arthera Testnet

### Chain ID

10243

### RPC URL

https://rpc-test.arthera.net

### Block Explorer URL

https://explorer-test.arthera.net

### Deployment Funds

No

**Comment by julienbrg** [comment]
Hello @mds1, I just sent 1 AA (native currency of Arthera) to [0x05f32B3cC3888453ff71B01135B34FF8e41263F2](https://explorer-test.arthera.net/address/0x05f32B3cC3888453ff71B01135B34FF8e41263F2) ([view tx](https://explorer-test.arthera.net/tx/0x69c85bf0a0ba991b2290dfba137f6143a035804dc2c01bb8d4c526838852d644)).

**Comment by mds1** [comment]
Done, thanks!
