### ISSUE TITLE
Deploy Multicall3 to SKALE Calypso Testnet

### ISSUE THREAD

**Issue by TheGreatAxios** [mds1/multicall#113]
### Chain Name

SKALE Calypso Testnet

### Chain ID

344106930

### RPC URL

https://staging-v3.skalenodes.com/v1/staging-utter-unripe-menkar

### Block Explorer URL

https://staging-utter-unripe-menkar.explorer.staging-v3.skalenodes.com/

### Deployment Funds

Yes

**Comment by mds1** [comment]
Done, thanks!
