### ISSUE TITLE
Deploy multicall3 to SKALE Chaos Testnet

### ISSUE THREAD

**Issue by TheGreatAxios** [mds1/multicall#114]
### Chain Name

SKALE Chaos Testnet

### Chain ID

1351057110

### RPC URL

https://staging-v3.skalenodes.com/v1/staging-fast-active-bellatrix

### Block Explorer URL

https://staging-fast-active-bellatrix.explorer.staging-v3.skalenodes.com/

### Deployment Funds

Yes

**Comment by mds1** [comment]
Done, thanks!
