### ISSUE TITLE
Deploy multicall3 to SKALE Europa Testnet

### ISSUE THREAD

**Issue by TheGreatAxios** [mds1/multicall#115]
### Chain Name

SKALE Europa Testnet

### Chain ID

476158412

### RPC URL

https://staging-v3.skalenodes.com/v1/staging-legal-crazy-castor

### Block Explorer URL

https://staging-legal-crazy-castor.explorer.staging-v3.skalenodes.com/

### Deployment Funds

Yes

**Comment by mds1** [comment]
Done, thanks!
