### ISSUE TITLE
Deploy multicall3 to SKALE Nebula Testnet

### ISSUE THREAD

**Issue by TheGreatAxios** [mds1/multicall#116]
### Chain Name

SKALE Nebula Testnet

### Chain ID

503129905

### RPC URL

https://staging-v3.skalenodes.com/v1/staging-faint-slimy-achird

### Block Explorer URL

https://staging-faint-slimy-achird.explorer.staging-v3.skalenodes.com/

### Deployment Funds

Yes

**Comment by mds1** [comment]
Done, thanks!
