### ISSUE TITLE
Deploy multicall3 to SKALE Psyche Testnet

### ISSUE THREAD

**Issue by TheGreatAxios** [mds1/multicall#117]
### Chain Name

SKALE Psyche Testnet

### Chain ID

1103198827

### RPC URL

https://staging-v3.skalenodes.com/v1/staging-old-mushy-saiph

### Block Explorer URL

https://staging-old-mushy-saiph.explorer.staging-v3.skalenodes.com/

### Deployment Funds

Yes

**Comment by mds1** [comment]
Done, thanks!
