### ISSUE TITLE
Deploy multicall3 to SKALE Titan Testnet

### ISSUE THREAD

**Issue by TheGreatAxios** [mds1/multicall#118]
### Chain Name

SKALE Titan Testnet

### Chain ID

1517929550

### RPC URL

https://staging-v3.skalenodes.com/v1/staging-aware-chief-gianfar

### Block Explorer URL

https://staging-aware-chief-gianfar.explorer.staging-v3.skalenodes.com/

### Deployment Funds

Yes

**Comment by mds1** [comment]
Done, thanks!
