### ISSUE TITLE
Deploy multicall3 to SKALE Calypso NFT Hub

### ISSUE THREAD

**Issue by TheGreatAxios** [mds1/multicall#119]
### Chain Name

SKALE Calypso NFT Hub

### Chain ID

1564830818

### RPC URL

https://mainnet.skalenodes.com/v1/honorable-steel-rasalhague

### Block Explorer URL

https://honorable-steel-rasalhague.explorer.mainnet.skalenodes.com/

### Deployment Funds

Yes

**Comment by mds1** [comment]
Done, thanks!
