### ISSUE TITLE
Deployment of MulticallV3 to Moonriver

### ISSUE THREAD

**Issue by not-reed** [mds1/multicall#12]
Explorer: https://moonriver.moonscan.io/

**Comment by mds1** [comment]
Any chance you could send deployment funds to 0x05f32B3cC3888453ff71B01135B34FF8e41263F2? I have not used this chain, so it will take me some time to figure out how to get funds on it. I would guess that $10 of funds should be more than enough and I can refund the excess

**Comment by albertov19** [comment]
Hey @mds1 I've sent 0.1 MOVR to the specified address: https://moonriver.moonscan.io/tx/0x9e3e64b08ce1e05196a8353878be38f82285b83336226deda282a15f7f00df7c

Thanks in advance! 😃 🚀

**Comment by mds1** [comment]
Deployed! README will be updated later today
 https://moonriver.moonscan.io/address/0xca11bde05977b3631167028862be2a173976ca11#code
