### ISSUE TITLE
Deploy multicall3 to SKALE Europa Liquidity Hub

### ISSUE THREAD

**Issue by TheGreatAxios** [mds1/multicall#120]
### Chain Name

SKALE Europa Liquidity Hub

### Chain ID

2046399126

### RPC URL

https://mainnet.skalenodes.com/v1/elated-tan-skat

### Block Explorer URL

https://elated-tan-skat.explorer.mainnet.skalenodes.com/

### Deployment Funds

Yes

**Comment by mds1** [comment]
Done, thanks!
