### ISSUE TITLE
Deploy multicall3 to SKALE Nebula Gaming Hub

### ISSUE THREAD

**Issue by TheGreatAxios** [mds1/multicall#121]
### Chain Name

SKALE Nebula Gaming Hub

### Chain ID

1482601649

### RPC URL

https://mainnet.skalenodes.com/v1/green-giddy-denebola

### Block Explorer URL

https://green-giddy-denebola.explorer.mainnet.skalenodes.com/

### Deployment Funds

Yes

**Comment by mds1** [comment]
Done, thanks!
