### ISSUE TITLE
Deploy multicall3 to SKALE Titan Community Hub

### ISSUE THREAD

**Issue by TheGreatAxios** [mds1/multicall#122]
### Chain Name

SKALE Titan Community Hub

### Chain ID

1350216234

### RPC URL

https://mainnet.skalenodes.com/v1/parallel-stormy-spica

### Block Explorer URL

https://parallel-stormy-spica.explorer.mainnet.skalenodes.com/

### Deployment Funds

Yes

**Comment by mds1** [comment]
Done, thanks!
