### ISSUE TITLE
XDC Testnet

### ISSUE THREAD

**Issue by 0xbeny** [mds1/multicall#128]
### Chain Name

XDC testnet

### Chain ID

51

### RPC URL

https://apothem.xdcrpc.com	

### Block Explorer URL

https://apothem.xdcscan.io/

### Deployment Funds

No

**Comment by GalaxySciTech** [comment]
https://devnetstats.apothem.network/devnet
https://devnetstats.apothem.network/subnet

add these please @mds1

**Comment by mds1** [comment]
I'd recommend funding the deployer account on the chains to speed up deployment. Alternatively you can deploy yourself using the presigned transaction. See https://github.com/mds1/multicall#new-deployments for more info on either approach

@GalaxySciTech If those are separate chains, please open one issue per chain with the requested information. It makes things much easier for me to find all the required information that way :)

**Comment by 0xbeny** [comment]
Testnet FAUCET is done: https://apothem.blocksscan.io/address/xdc05f32b3cc3888453ff71b01135b34ff8e41263f2#transactions

**Comment by nitishpatel** [comment]
Not working, it says multicall3 is not deployed on this network

**Comment by mds1** [comment]
Closing as stale since no deployment funds were provided
