### ISSUE TITLE
Deploy to Neon EVM Mainnet

### ISSUE THREAD

**Issue by joehquak** [mds1/multicall#129]
### Chain Name

Neon Mainnet

### Chain ID

245022934

### RPC URL

https://neon-proxy-mainnet.solana.p2p.org

### Block Explorer URL

https://www.neonscan.org

### Deployment Funds

Yes

**Comment by joehquak** [comment]
https://neonscan.org/tx/0xa1efdb11a716d0e20a6c628199835cc1805a2573e101b67e0f39f6eda4e5569c

**Comment by mds1** [comment]
Done, thanks!

**Comment by joehquak** [comment]
Amazing thanks again!

**Comment by joehquak** [comment]
@mds1 Would it be possible to verify the source code please? Thanks in advance!

Endpoint for verification:
`https://api.neonscan.org/hardhat/verify`

**Comment by mds1** [comment]
You can find verification instructions here: https://github.com/mds1/multicall#contract-verification :)

**Comment by joehquak** [comment]
Worked a treat, thank you!
