### ISSUE TITLE
Deploy on LUKSO Mainnet

### ISSUE THREAD

**Issue by YamenMerhi** [mds1/multicall#140]
### Chain Name

LUKSO Mainnet

### Chain ID

42

### RPC URL

https://rpc.lukso.gateway.fm

### Block Explorer URL

https://explorer.execution.mainnet.lukso.network

### Deployment Funds

Yes

**Comment by YamenMerhi** [comment]
As Kovan is officially deprecated, LUKSO Mainnet used the `chainId` 42.
Kovan needs to be replaced by LUKSO Mainnet as chainId 42 in: https://multicall3.com/deployments

**Comment by mds1** [comment]
Done, but why re-use a chain ID instead of just choosing a new one? Now people who still have kovan data can replay kovan transactions on LUKSO mainnet, which of course is not good

**Comment by YamenMerhi** [comment]
The chain is heavily attached to `42` for many reasons, it was launched on 4/20/2023 at 4:20pm UTC with a 42M LYX supply. As for replay attacks, after research and analysis, we decided that the risk is minimal. Going with 42 as a chainId won't be an issue as Kovan was a testnet; ideally, you shouldn't use the same keys you used on a testnet to interact on a Mainnet.

**Comment by YamenMerhi** [comment]
Maybe @mds1 you should consider removing Kovan from `https://www.multicall3.com/deployments` as it points to a dead explorer and as I said Kovan is deprecated.

**Comment by mds1** [comment]
I'm going to leave it in for posterity—there are now many deprecated testnets, but it doesn't hurt to keep the records
