### ISSUE TITLE
Deploy official Multicall3 on meter.io

### ISSUE THREAD

**Issue by xiaohanzhu** [mds1/multicall#141]
### Chain Name

Meter

### Chain ID

82

### RPC URL

https://rpc.meter.io

### Block Explorer URL

https://scan.meter.io

### Deployment Funds

Yes

**Comment by xiaohanzhu** [comment]
Meter uses randomized nonce for EOA addresses.  The deployment address maybe different from other chains

**Comment by mds1** [comment]
Can you explain more on how the randomized nonce works? Also, if the address will be different as a result, I'd prefer to have someone else deploy it and I can still add it to the deploy log—the rationale here is that (1) if the address will be different, it doesn't matter who deploys it, and (2) that way we ensure the deployer account with nonce 0 is preserved in case it becomes possible to get the same address in the future.

This is what we did for zkSync—someone deployed it at the same address on both zkSync mainnet and testnet, and I added that to the deploy file

**Comment by xiaohanzhu** [comment]
Talked with our devs.  The randomized nonce just means you could use any nonce as long as the tx hash is different and we don't maintain nonce in each EOA account.  However, that means you could force the nonce to a number (like 0) when you send the tx.  In that case, you will still be able to deploy to the same address.  For example, deploy with Remix and use metamask to customize the nonce to 0.  Hope this is clear.

**Comment by xiaohanzhu** [comment]
> Can you explain more on how the randomized nonce works? Also, if the address will be different as a result, I'd prefer to have someone else deploy it and I can still add it to the deploy log—the rationale here is that (1) if the address will be different, it doesn't matter who deploys it, and (2) that way we ensure the deployer account with nonce 0 is preserved in case it becomes possible to get the same address in the future.
> 
> This is what we did for zkSync—someone deployed it at the same address on both zkSync mainnet and testnet, and I added that to the deploy file

Could you deploy it on your end so that it will have the same address as other networks?  Thanks a lot

**Comment by mds1** [comment]
Will do, do you mind funding the deployer account? Just went to deploy since the above request says it's funded, but it appears the balance is 0:

https://scan.meter.io/address/0x05f32b3cc3888453ff71b01135b34ff8e41263f2

```
$ cast balance 0x05f32B3cC3888453ff71B01135B34FF8e41263F2 --rpc-url https://rpc.meter.io
0
```

**Comment by xiaohanzhu** [comment]
> Will do, do you mind funding the deployer account? Just went to deploy since the above request says it's funded, but it appears the balance is 0:
> 
> https://scan.meter.io/address/0x05f32b3cc3888453ff71b01135b34ff8e41263f2
> 
> ```
> $ cast balance 0x05f32B3cC3888453ff71B01135B34FF8e41263F2 --rpc-url https://rpc.meter.io
> 0
> ```

Sorry, should be there now.  Both on mainnet and testnet.  Thank you!
