### ISSUE TITLE
Please deploy on Oasis Sapphire

### ISSUE THREAD

**Issue by CedarMist** [mds1/multicall#144]
### Chain Name

Oasis Sapphire

### Chain ID

0x5afe (23294)

### RPC URL

https://sapphire.oasis.io

### Block Explorer URL

https://explorer.sapphire.oasis.io/

### Deployment Funds

Yes

**Comment by CedarMist** [comment]
I tried deploying using `cast` but we get an error:

    ProviderError: client: transaction check failed: runtime error: module: core code: 1
    message: malformed transaction: chain ID None, expected Some(23294)

Presumably this means you need to manually deploy it.

**Comment by mds1** [comment]
Yea that means the chain requires [EIP-155](https://eips.ethereum.org/EIPS/eip-155), and the presigned transaction does of course does not sign over a chain ID. 

Just deployed, thanks!
