### ISSUE TITLE
Canto Testnet

### ISSUE THREAD

**Issue by dsudit01** [mds1/multicall#148]
### Chain Name

Canto Testnet

### Chain ID

7701

### RPC URL

https://canto-testnet.plexnode.wtf

### Block Explorer URL

https://testnet.tuber.build

### Deployment Funds

Yes

**Comment by mds1** [comment]
Should be able to deploy this week, note that you can also deploy yourself with a pre-signed transaction as documented here: https://github.com/mds1/multicall#new-deployments

**Comment by mds1** [comment]
Done, thanks!
