### ISSUE TITLE
Deployment of MulticallV3 to Moonbase Alpha

### ISSUE THREAD

**Issue by albertov19** [mds1/multicall#15]
Explorer: https://moonbase.moonscan.io/

I've funded the specified address with 5 DEV tokens (TestNet): https://moonbase.moonscan.io/tx/0xb38818de51a430b5acad9cae072431618619786af35df1f9a3cee7518330fa46

Thanks in advance :)

**Comment by mds1** [comment]
Deployed! README will be updated later today

https://moonbase.moonscan.io/address/0xca11bde05977b3631167028862be2a173976ca11#code
