### ISSUE TITLE
Deployment of MulticallV3 to ThunderCore Testnet

### ISSUE THREAD

**Issue by kevin-thundertoken** [mds1/multicall#151]
### Chain Name

ThunderCore

### Chain ID

18

### RPC URL

https://testnet-rpc.thundercore.com

### Block Explorer URL

https://explorer-testnet.thundercore.com/

### Deployment Funds

Yes

**Comment by mds1** [comment]
Are there certain gas prices that must be used? The deploy transaction is error with "transaction underpriced" when using MetaMask

**Comment by mds1** [comment]
Closing as stale since there's been no response
