### ISSUE TITLE
Deploy to Optimism Sepolia

### ISSUE THREAD

**Issue by nitaliano** [mds1/multicall#152]
### Chain Name

OP Sepolia

### Chain ID

[11155420](https://community.optimism.io/docs/useful-tools/networks/#op-sepolia)

### RPC URL

https://sepolia.optimism.io

### Block Explorer URL

https://optimism-sepolia.blockscout.com/

### Deployment Funds

[Yes](https://optimism-sepolia.blockscout.com/tx/0x3bf0727d0cb59559442831082e51f1388eae77b39e0263c53dc24fe775554559)

**Comment by mds1** [comment]
I should be able to get to this tomorrow, but there is also a presigned tx that should work if you want to deploy yourself sooner. You can find instructions for using that here: https://github.com/mds1/multicall#new-deployments

**Comment by mds1** [comment]
Done, thanks!
