### ISSUE TITLE
multicall3 is not verified on canto

### ISSUE THREAD

**Issue by oxSaturn** [mds1/multicall#167]
Can someone get it verified on canto https://tuber.build/address/0xcA11bde05977b3631167028862bE2a173976CA11?tab=contract?

**Comment by mds1** [comment]
You can find verification instructions in the README here: https://github.com/mds1/multicall#contract-verification

**Comment by mds1** [comment]
Closing as verification instructions are above, and the canto verification page seems to have a bug where I can't select a solc version to verify with 
<img width="1073" alt="image" src="https://github.com/mds1/multicall/assets/17163988/aede006b-b307-4593-81b0-bb6035bb2bc4">
