### ISSUE TITLE
Deployment of MulticallV3 to Boba, Cronos, Aurora, Astar, Metis

### ISSUE THREAD

**Issue by kykungz** [mds1/multicall#17]
Hi there, I'm Jacky from [Ape Board](https://apeboard.finance)!

Ape Board is heavily using Multicall and really love the improvements on MulticallV3!

Do you by any chance have some time to deploy it on Boba, Cronos, Aurora, Astar and Metis?

I saw that the deployment gas used was around 872,776 (rounded up to 900,000),
So I've sent along some deployment costs to `0x05f32B3cC3888453ff71B01135B34FF8e41263F2` on these chains.

| Chain  |   Funds sent | Transaction                                                                                                                                                          |
| ------ | -----------: | :------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| BOBA   |   0.0009 ETH | [https://blockexplorer.boba.network/tx/0xc3242...09a696](https://blockexplorer.boba.network/tx/0xc32427999e065f18c73570dad16b70b5de89c77e06c5a6d80a24e6646609a696)   |
| CRONOS |      4.5 CRO | [https://cronos.org/explorer/tx/0x193fd...72e92b](https://cronos.org/explorer/tx/0x193fd1ab666226aa6513d093fdb907769ed0c97958545aa38ee0faf42172e92b)                 |
| AURORA | 0.000027 ETH | [https://aurorascan.dev/tx/0x0af59...1ac04e](https://aurorascan.dev/tx/0x0af59acdd13df8467569ff367130f8305cf7bbad52a1885dc9a2b2a5ff1ac04e)                           |
| ASTAR  |  0.0009 ASTR | [https://blockscout.com/astar/tx/0xe2d31...cbff25](https://blockscout.com/astar/tx/0xe2d31b33b2cb4f1494a27723ad187628a66a453cf63a5e64b23dca9e49cbff25)               |
| METIS  | 0.0072 METIS | [https://andromeda-explorer.metis.io/tx/0x18149...fdb4e8](https://andromeda-explorer.metis.io/tx/0x18149120b54a2ad08891a9518354e1f6f53885c7c197284e3665027980fdb4e8) |

Please let me know if the funds are not enough, so I could send more!

**Comment by mds1** [comment]
Awesome, thank you! I may have time to deploy today, but otherwise I won't deploy until around mid next week. Either way I'll update this issue once deploys are complete

**Comment by mds1** [comment]
Any chance you could send a little more on Boba? Just tried deploying and when using the gas price provided by the node, the gas estimation fails with `insufficient funds for gas * price + value`

**Comment by mds1** [comment]
Same issue for Aurora 🙂

Cronos was deployed successfully, about to try the last two

**Comment by mds1** [comment]
Same issue for Aurora, Astar, and Metis 🙂

Guessing it's just variable gas prices from the time you did the estimation, but Cronos was deployed successfully!

**Comment by mikephul** [comment]
Hi @mds1,

Sending more deployment fund for Boba, Aurora Astar, Metis! Thank you for the Cronos deployment :)

Chain | Funds sent | Transaction
-- | -- | --
BOBA | 0.003 ETH | https://blockexplorer.boba.network/tx/0x5a6debc85add382b65f66dae5efd4e86bd04cc8c6d60a717fbe056175623deda/internal-transactions
AURORA | 0.0003 ETH | https://explorer.mainnet.aurora.dev/tx/0xb7b3c8b2767b1f4063776352f3e92a6ca715a9deb66312e0daddde667aea873b/internal-transactions
ASTAR | 5 ASTR | https://blockscout.com/astar/tx/0x001ec3bc6e5a12a3f1a23f76b261e745e7f589e95a47a4347a186aceb5f4cbaa/internal-transactions
METIS | 0.01 METIS | https://andromeda-explorer.metis.io/tx/0x47a70f7ae61e46c9d40b9ebc616a033c4b2beb9905772b957467b863420a0ea3/internal-transactions

**Comment by mds1** [comment]
Thanks @mikephul! Deployed to Boba, Aurora, and Astar. On Metis I have 0.0172 METIS but the deploy cost is estimated at ~0.045 METIS currently. I'm not sure if this is a temporary gas spike or not (since I'm not really familiar with Metis), so up to you if I should wait it out of if you want to send additional funds

**Comment by mds1** [comment]
Just deployed to Metis, so all four of these are now complete!
