### ISSUE TITLE
Please deploy on wanchain mainnet, and I have transfered 0.1 WAN for gas to deploy address.

### ISSUE THREAD

**Issue by lolieatapple** [mds1/multicall#170]
### Chain Name

Wanchain Mainnet

### Chain ID

888

### RPC URL

https://gwan-ssl.wandevs.org:56891

### Block Explorer URL

https://wanscan.org

### Deployment Funds

Yes

**Comment by mds1** [comment]
Sorry for the delay here, I should be able to do this on Tuesday. If you need it sooner you can also deploy using the pre-signed transaction in the README: https://github.com/mds1/multicall#new-deployments

**Comment by mds1** [comment]
Done, thanks!
