### ISSUE TITLE
Deploy on Chiliz Chain

### ISSUE THREAD

**Issue by nstylo** [mds1/multicall#176]
### Chain Name

Chiliz Chain

### Chain ID

88888

### RPC URL

https://chiliz.publicnode.com/

### Block Explorer URL

https://scan.chiliz.com/

### Deployment Funds

No

**Comment by nstylo** [comment]
Hi @mds1, would love to have multicall3 on Chiliz. I am definitly willing to fund the deployment. How much funds will this take though, how can I estimate this?

**Comment by mds1** [comment]
Hi, please see https://github.com/mds1/multicall#new-deployments for more info on the funding amount needed. If you can use the presigned transaction, you may deploy yourself and will only need to send 0.1 ETH to the deployer

**Comment by nstylo** [comment]
Your presigned tx won't work when dealing with chains having EIP-155 enabled.

**Comment by nstylo** [comment]
I deployed myself, it has obviously a different contract address from the canonical one:

https://scan.chiliz.com/address/0x0E6a1Df694c4be9BFFC4D76f2B936bB1A1df7fAC/contracts#address-tabs

**Comment by nstylo** [comment]
You'll have enough funds on your address though to redeploy if you like.

**Comment by mds1** [comment]
Done, thanks!
