### ISSUE TITLE
Request of Deploy on ZetaChain Athens 3 Testnet

### ISSUE THREAD

**Issue by andrewzhang97** [mds1/multicall#180]
### Chain Name

ZetaChain Athens 3 Testnet

### Chain ID

7001

### RPC URL

https://rpc.ankr.com/zetachain_evm_athens_testnet	

### Block Explorer URL

https://explorer.zetachain.com/

### Deployment Funds

Yes

**Comment by mds1** [comment]
Done, thanks!
