### ISSUE TITLE
Request to deploy multicall on X1

### ISSUE THREAD

**Issue by m66260** [mds1/multicall#184]
### Chain Name

X1

### Chain ID

195

### RPC URL

https://testrpc.x1.tech

### Block Explorer URL

https://www.oklink.com/x1-test

### Deployment Funds

Yes

**Comment by mds1** [comment]
Looks like this is already deployed: https://www.oklink.com/x1-test/address/0xca11bde05977b3631167028862be2a173976ca11/contract
