### ISSUE TITLE
Request deploy lumiterra layer3, arbitrum orbit chain

### ISSUE THREAD

**Issue by alberthuang24** [mds1/multicall#187]
### Chain Name

Lumiterra Layer3

### Chain ID

94168

### RPC URL

https://node1.layerlumi.com

### Block Explorer URL

https://scan.layerlumi.com/tx/0xabc74cdf6251be6d0d1471848d168b208e23fe92f61b889d4b066853daf77a88

### Deployment Funds

Yes

**Comment by mds1** [comment]
Done, thanks!
