### ISSUE TITLE
Deployment of MulticallV3 to Fuse Network

### ISSUE THREAD

**Issue by DefiDebauchery** [mds1/multicall#19]
https://fuse.io is a low-cost EVM chain that we at Beefy Finance have contracts deployed on, and would like to take advantage of the static address.

I've [funded](https://explorer.fuse.io/tx/0x04cb1a6a35c87120d46f0a7ceaf22f2ca6a3a3e6c215cee869c94d3532a627e4/internal-transactions) the `0x05f32B3cC3888453ff71B01135B34FF8e41263F2` address with 1 FUSE, which should be more than enough to deploy the MulticallV3 contract. Chain ID 122

Thank you!

**Comment by mds1** [comment]
Done, thanks! https://explorer.fuse.io/address/0xcA11bde05977b3631167028862bE2a173976CA11/contracts
