### ISSUE TITLE
Areon Network Testnet

### ISSUE THREAD

**Issue by emrahsky** [mds1/multicall#190]
### Chain Name

Areon Network Testnet

### Chain ID

462

### RPC URL

https://testnet-rpc.areon.network

### Block Explorer URL

https://areonscan.com

### Deployment Funds

Yes

**Comment by mds1** [comment]
I won’t be able to deploy for another 1-2 weeks, so I’d recommend using the presigned transaction described in the README: https://github.com/mds1/multicall#new-deployments

**Comment by mds1** [comment]
Done, thanks!
