### ISSUE TITLE
Deploy to Mode

### ISSUE THREAD

**Issue by spacesailor24** [mds1/multicall#197]
### Chain Name

Mode Mainnet

### Chain ID

34443

### RPC URL

https://rpc.mode.network

### Block Explorer URL

https://explorer.mode.network

### Deployment Funds

No

**Comment by spacesailor24** [comment]
I will be funding the deployment address, just waiting for funds to arrive

**Comment by spacesailor24** [comment]
`0.015 ETH` sent to `0x05f32B3cC3888453ff71B01135B34FF8e41263F2` - [Tx info](https://explorer.mode.network/tx/0x7e08060933a0965477150671f78fc2bf51e3fc01ad5733768e33785583991e96)

**Comment by mds1** [comment]
Done, thanks!
