### ISSUE TITLE
Deployment: Areon Network Mainnet

### ISSUE THREAD

**Issue by alperencantez** [mds1/multicall#199]
### Chain Name

Areon Network Mainnet

### Chain ID

463

### RPC URL

https://mainnet-rpc.areon.network

### Block Explorer URL

https://areonscan.com

### Deployment Funds

Yes

**Comment by mds1** [comment]
Done, thanks!

**Comment by emrahsky** [comment]
Hey, Can you please correct the chain id for Areon Network Mainnet from 464 to 463? It was entered incorrectly.

**Comment by emrahsky** [comment]
> Done, thanks!


Hey, Can you please correct the chain id for Areon Network Mainnet from 464 to 463? It was entered incorrectly.

**Comment by mds1** [comment]
Oops, thanks for catching. Fixed in 49ac24b
