### ISSUE TITLE
Deployment of MulticallV3 to Flare's Coston & Songbird networks

### ISSUE THREAD

**Issue by alexdupre** [mds1/multicall#20]
Please deploy MulticallV3 on the test and canary networks of Flare.
I've sent you more than enough to pay for deploy costs, you can set 25 gwei as gas price and no priority fee.

| Chain | Explorer | Funds sent | Transaction |
| --- | --- | --- | --- |
| Coston |  https://coston-explorer.flare.network/ | 1 CFLR | [Link to explorer](https://coston-explorer.flare.network/tx/0xd349c23cf519b35b806859abc5ff7903e690462f997d187be1c3adcea590c222/internal-transactions) |
| Songbird | https://songbird-explorer.flare.network/ | 1 SGB | [Link to explorer](https://songbird-explorer.flare.network/tx/0x26b6f83ee4ce9e9e94843201e234d4ee1e979e26ba00fb6894dd9c89306f065a/internal-transactions) |

**Comment by mds1** [comment]
Done! Readme has been updated 🙂

**Comment by alexdupre** [comment]
Thanks!
