### ISSUE TITLE
Deployment: Kroma Mainnet Network

### ISSUE THREAD

**Issue by AleksandarDevic** [mds1/multicall#200]
### Chain Name

Kroma Mainnet

### Chain ID

255

### RPC URL

https://api.kroma.network

### Block Explorer URL

https://kromascan.com

### Deployment Funds

Yes

**Comment by mds1** [comment]
Kroma is an OP Stack fork and has Multicall3 as a [preinstall](https://specs.optimism.io/protocol/preinstalls.html), so closing this as completed
