### ISSUE TITLE
Deployment: Stylus Testnet

### ISSUE THREAD

**Issue by afosan** [mds1/multicall#204]
### Chain Name

Stylus Testnet

### Chain ID

23011913

### RPC URL

https://stylus-testnet.arbitrum.io/rpc

### Block Explorer URL

https://stylus-testnet-explorer.arbitrum.io/

### Deployment Funds

Yes

**Comment by afosan** [comment]
I actually tried to deploy it myself with the following as instructed.
```
# `TX` is the signed transaction above.
# `RPC_URL` is the RPC URL of the chain you want to deploy to.
cast publish $TX --rpc-url $RPC_URL
```

Unfortunately, it failed as RPC does not accept non-EIP155 transactions.
```
Error: 
(code: -32000, message: only replay-protected (EIP-155) transactions allowed over RPC, data: None)
```

I could not find another public RPC, and have no time to setup a node myself for the following days. I can only think of two solutions:
1) Please kindly send the transaction with the chain id explicitly set.
2) I contacted Offchain labs on discord so hopefully they can broadcast the signed transaction to the network, circumventing EIP155 limitation with the public RPC.

Thanks!

**Comment by mds1** [comment]
Done, thanks!
