### ISSUE TITLE
Deploy to ZetaChain Mainnet Beta

### ISSUE THREAD

**Issue by fadeev** [mds1/multicall#209]
### Chain Name

ZetaChain

### Chain ID

7000

### RPC URL

https://zetachain-evm.blockpi.network/v1/rpc/public

### Block Explorer URL

https://explorer.zetachain.com/

### Deployment Funds

Yes

**Comment by mds1** [comment]
Done, thanks!

**Comment by fadeev** [comment]
@mds1 thank you! 🙏
