### ISSUE TITLE
Deployment of MulticallV3 to OKC and HECO

### ISSUE THREAD

**Issue by heki-ru** [mds1/multicall#21]
OKC (previously known as OEC, OKEX, EXCHAIN)
https://www.oklink.com/en/okc
Sent 0.01 OKT to 0x05f32B3cC3888453ff71B01135B34FF8e41263F2
It's possible to use 0.1 gwei for transaction and it will go through

HECO
https://hecoinfo.com/
Sent 0.05 HT to 0x05f32B3cC3888453ff71B01135B34FF8e41263F2
For HECO gas price is 2.25 gwei

Thank you in advance

**Comment by mds1** [comment]
Done!

Note that verifying the contract on OKC fails with `TypeError: "basefee" is not supported by the VM version`, but it is deployed and should still work.
