### ISSUE TITLE
Omax Network Integration

### ISSUE THREAD

**Issue by DaRabus** [mds1/multicall#215]
### Chain Name

Omax Mainnet

### Chain ID

311

### RPC URL

https://mainapi.omaxray.com

### Block Explorer URL

https://omaxscan.com/

### Deployment Funds

Yes

Funds sent:
http://omaxscan.com/address/0x05f32B3cC3888453ff71B01135B34FF8e41263F2

https://chainlist.org/chain/311

**Comment by DaRabus** [comment]
@mds1 Any chance to get that deployed?

**Comment by mds1** [comment]
Done, thanks!
