### ISSUE TITLE
Archive Data

### ISSUE THREAD

**Issue by radisa-bogdanovic** [mds1/multicall#219]
Ethereum Mainnet

If i get request for multicall data on specific block wich happened in 2023 i getting result as i should, but if i request data for Eth from 2019 im getting no data
Is this because there is no data for that time so i can return emty result or i making some mistake.? I'm using this multicontractAddress : 0xcA11bde05977b3631167028862bE2a173976CA11
Also im using Merkle as provider 
Basicaly i cant get a data before deployment of multiContractAddress on etherscan

**Comment by mds1** [comment]
This is correct, you will not be able to use Multicall3 to read historical data from before Multicall3 was deployed. A workaround is to use geth's state overrides and place the Multicall3 bytecode at the expected address as part of your call
