### ISSUE TITLE
Deployment of MulticallV3 to RSK

### ISSUE THREAD

**Issue by kraikov** [mds1/multicall#22]
[rsk.co](https://www.rsk.co/) is a low-cost EVM chain that is built on top of Bitcoin.

I've the 0x05f32B3cC3888453ff71B01135B34FF8e41263F2 address on both [testnet](https://explorer.testnet.rsk.co/tx/0x37ab7a7a18652f0051c74853d00c1a429936f4ac8700fe4a6e43c2a959b0371f) and [mainnet](https://explorer.rsk.co/tx/0xd3353919b6833b98d544e539ba1413f5f2c28f066b41ef74e1808b46ef459b66).

ChainID:
```
rskTestnet: 31
rsk: 30
```

Thank you!

**Comment by mds1** [comment]
Deployed, and README updated—thanks!
