### ISSUE TITLE
Shibarium Network Integration

### ISSUE THREAD

**Issue by DaRabus** [mds1/multicall#220]
### Chain Name

Shibarium

### Chain ID

109

### RPC URL

https://www.shibrpc.com

### Block Explorer URL

https://www.shibariumscan.io/

### Deployment Funds

Yes

Funds sent:
https://www.shibariumscan.io/address/0x05f32B3cC3888453ff71B01135B34FF8e41263F2

https://chainlist.org/chain/109

btw @mds1  Is it possible to get back the leftover funds, also maybe from the OMAX chain ^^
https://omaxscan.com/address/0x05f32B3cC3888453ff71B01135B34FF8e41263F2

**Comment by mds1** [comment]
Done, and funds have been returned on both chains!
