### ISSUE TITLE
Deploy Multicall3 on Blast Mainnet

### ISSUE THREAD

**Issue by markmifsud2000** [mds1/multicall#222]
### Chain Name

Blast-Mainnet

### Chain ID

81457

### RPC URL

https://rpc.blast.io/

### Block Explorer URL

https://blastscan.io/

### Deployment Funds

No

**Comment by mds1** [comment]
Looks like it was already been deployed on Blast using the presigned transactions: https://blastscan.io/address/0xca11bde05977b3631167028862be2a173976ca11
