### ISSUE TITLE
Deploy Multicall3 on Mantle Sepolia

### ISSUE THREAD

**Issue by ash-jyc** [mds1/multicall#226]
### Chain Name

Mantle Sepolia

### Chain ID

5003

### RPC URL

https://rpc.sepolia.mantle.xyz

### Block Explorer URL

https://explorer.sepolia.mantle.xyz/

### Deployment Funds

No

**Comment by georgeciubotaru** [comment]
@mds1  Deployment funds https://explorer.sepolia.mantle.xyz/tx/0xe692f1b9eb3484b9d891d147fe3eef5969c2eb7f76252dedb54c02cb2a437736

**Comment by mds1** [comment]
Done, thanks!
