### ISSUE TITLE
Filecoin Calibration (testnet)

### ISSUE THREAD

**Issue by crystalbit** [mds1/multicall#229]
### Chain Name

Filecoin - Calibration testnet

### Chain ID

314159

### RPC URL

https://rpc.ankr.com/filecoin_testnet

### Block Explorer URL

https://calibration.filscan.io/

### Deployment Funds

Yes

**Comment by crystalbit** [comment]
I tried myself but couldn't make not legacy tx - legacy is not supported there

**Comment by mds1** [comment]
Done, thanks!
