### ISSUE TITLE
Deploy to Evmos and Evmos testnet

### ISSUE THREAD

**Issue by akramhussein** [mds1/multicall#23]
[https://evmos.org/](Evmos) is a new Polkadot EVM compatible chain.

I've funded the testnet deployer EOA with testnet EVMOS and will try and fund mainnet EOA too.

**Evmos Mainnet:** 

Chain ID: `9001` 
Node RPC Url: https://eth.bd.evmos.org:8545

**Evmos Testnet:** 

Chain ID: `9000` 
Node RPC Url: https://eth.bd.evmos.dev:8545 (note .dev (testnet) vs .org)

**Comment by mds1** [comment]
Deployed to testnet, once the deployer account is funded for mainnet Evmos I'll do that one too

**Comment by akramhussein** [comment]
Done. If it's not enough let me know.

Realised I overcooked it with the `BNB` and sent way too much!

**Comment by mds1** [comment]
Mainnet deployed too—thanks! The contract verification is hanging so I'll try that again later before updating the README.

Looks like the BNB was sent from an exchange address—if you give me a refund address I can send the remaining balance back 🙂

**Comment by akramhussein** [comment]
`0xe7Dae745A61f213de89aa2e3CbEfaC22EC99Cc67`

Thanks!
