### ISSUE TITLE
Deploy multicall3 on PlayFi Albireo testnet

### ISSUE THREAD

**Issue by Archethect** [mds1/multicall#232]
### Chain Name

PlayFi Albireo testnet

### Chain ID

1612127

### RPC URL

https://albireo-rpc.playfi.ai

### Block Explorer URL

https://albireo-explorer.playfi.ai

### Deployment Funds

Yes

**Comment by Archethect** [comment]
@mds1 @xalexec

PlayFi is a new ZKStack chain, inhertining the same zkEVM properties as zkSync.
Would it be possible to deploy Multicall3 here? 

@xalexec I did send some funds to 0xEcB55A56360ecaD5ae94bb5f3C7f7f5244E90453 as this was the wallet you used to fund the deployments on the zkSync chains.

https://github.com/mds1/multicall/issues/76

**Comment by xalexec** [comment]
https://albireo-explorer.playfi.ai/address/0xF9cda624FBC7e059355ce98a31693d299FACd963

the explorer api is update,I can't verify the source code,I will try to update my dependencies

**Comment by Archethect** [comment]
@xalexec I was able to verify it.

Much appreciated for your time and effort. I will add a new entry in the deployments to reflect this deploy.
