### ISSUE TITLE
Optimism Sepolia Verification Required

### ISSUE THREAD

**Issue by kaleb-keny** [mds1/multicall#234]
### Chain Name

Optimism Sepolia

### Chain ID

11155420

### RPC URL

https://sepolia.optimism.io

### Block Explorer URL

https://sepolia-optimism.etherscan.io

### Deployment Funds

Yes

**Comment by kaleb-keny** [comment]
https://sepolia-optimism.etherscan.io/address/0xaf5b019ae92a5ad74740135da4e136bb77c9c703#code it is not a explorer issue, as i managed to verify the same version

**Comment by mds1** [comment]
All info you need for contract verification can be found in the README: https://github.com/mds1/multicall?tab=readme-ov-file#contract-verification

**Comment by kaleb-keny** [comment]
@mds1 appreciate it https://sepolia-optimism.etherscan.io/address/0xcA11bde05977b3631167028862bE2a173976CA11#code it's done
