### ISSUE TITLE
Please deploy Multicall3 on Linea Sepolia

### ISSUE THREAD

**Issue by thedarkjester** [mds1/multicall#235]
### Chain Name

Linea Sepolia

### Chain ID

59141

### RPC URL

https://rpc.sepolia.linea.build

### Block Explorer URL

https://sepolia.lineascan.build/

### Deployment Funds

Yes

**Comment by thedarkjester** [comment]
will need to rerequest this later

**Comment by mds1** [comment]
If possible, I'd suggest deploying with the [pre-signed transaction](https://github.com/mds1/multicall?tab=readme-ov-file#new-deployments), as I likely won't be able to deploy until the end of this week. If you go this route, **be careful and fully read the linked docs**, to make sure the nonce is not burned :)

**Comment by mds1** [comment]
Done, thanks!

**Comment by thedarkjester** [comment]
thank you kindly
