### ISSUE TITLE
Deploy Multicall3 for Zircuit testnet

### ISSUE THREAD

**Issue by skyline9981** [mds1/multicall#237]
### Chain Name

Zircuit testnet

### Chain ID

48899

### RPC URL

https://zircuit1.p2pify.com/

### Block Explorer URL

https://explorer.zircuit.com/

### Deployment Funds

Yes

**Comment by mds1** [comment]
I will aim to deploy by the end of this week

**Comment by mds1** [comment]
Done, thanks!
