### ISSUE TITLE
 Deployment of MulticallV3 to ThunderCore

### ISSUE THREAD

**Issue by scottt** [mds1/multicall#24]
* Block Explorer for ThunderCore: https://viewblock.io/thundercore/
* Already sent funds for gas to `0x05f32B3cC3888453ff71B01135B34FF8e41263F2`
https://viewblock.io/thundercore/tx/0x89795e4d1f69faa5070828646eee27080bd3bc88051f8add57dde31752dcfc30
* Chain information: https://chainlist.org/chain/108

Really appreciate you took the time to mine the distinct `0xCA11....CA11`  deployment address for `Multicall3` :)

**Comment by mds1** [comment]
The contract verification errors but it is now deployed—thanks!

**Comment by scottt** [comment]
Thanks @mds1!
