### ISSUE TITLE
Deploy to Metis Andromeda

### ISSUE THREAD

**Issue by t0mcr8se** [mds1/multicall#245]
### Chain Name

Metis Andromeda

### Chain ID

1088

### RPC URL

https://andromeda.metis.io/

### Block Explorer URL

https://andromeda-explorer.metis.io

### Deployment Funds

Yes

**Comment by mds1** [comment]
Was this chain started as a fork of another chain? Seems Multicall3 was deployed 2y ago in this transaction: https://andromeda-explorer.metis.io/tx/0x2f8ee0330c6df7f2787e10687385690255d549c402ad7ce2fc4ee7171b8e6903

And the contract is here https://andromeda-explorer.metis.io/address/0xcA11bde05977b3631167028862bE2a173976CA11?tab=contract
