### ISSUE TITLE
Deploy to Metis Sepolia

### ISSUE THREAD

**Issue by t0mcr8se** [mds1/multicall#246]
### Chain Name

Metis Sepolia

### Chain ID

59902

### RPC URL

https://sepolia.metisdevops.link/

### Block Explorer URL

https://sepolia-explorer.metisdevops.link/

### Deployment Funds

Yes

**Comment by mds1** [comment]
Looks like someone already deployed using the presigned transaction! https://sepolia-explorer.metisdevops.link/address/0xcA11bde05977b3631167028862bE2a173976CA11?tab=contract
