### ISSUE TITLE
Deployment of MulticallV3 to ThunderCore Testnet

### ISSUE THREAD

**Issue by rogerhsu-tt** [mds1/multicall#25]
- Block Explorer for ThunderCore Testnet: https://explorer-testnet.thundercore.com/
- Already sent funds for gas to `0x05f32B3cC3888453ff71B01135B34FF8e41263F2` - https://explorer-testnet.thundercore.com/tx/0x9fb1111dc006657870858811767c0f03e20063099f291773e49264bf4e20279e
- Chain information: https://chainlist.org/chain/18

Really appreciate you took the time to mine the distinct `0xCA11....CA11` deployment address for Multicall3 :)

**Comment by mds1** [comment]
Done, thanks!
