### ISSUE TITLE
Deploy Multicall3 on SEI EVM Devnet

### ISSUE THREAD

**Issue by SocksNFlops** [mds1/multicall#252]
### Chain Name

Sei EVM Devnet

### Chain ID

713715

### RPC URL

https://evm-rpc-arctic-1.sei-apis.com

### Block Explorer URL

https://seistream.app/

### Deployment Funds

Yes

**Comment by SocksNFlops** [comment]
Deployed and verified here: https://seitrace.com/address/0xcA11bde05977b3631167028862bE2a173976CA11?tab=contract

**Comment by mds1** [comment]
Thank you! Have this added to `deployments.json` locally and will push soon
