### ISSUE TITLE
Request Deployment for DreyerX Mainnet

### ISSUE THREAD

**Issue by billalxcode** [mds1/multicall#255]
### Chain Name

DreyerX Mainnet

### Chain ID

23451

### RPC URL

https://rpc.dreyerx.com

### Block Explorer URL

https://scan.dreyerx.com

### Deployment Funds

Yes

**Comment by mds1** [comment]
Contrary to the issue description, deployment funds have not been sent, so I have not deployed
```
$ cast balance 0x05f32b3cc3888453ff71b01135b34ff8e41263f2 --rpc-url https://rpc.dreyerx.com
0
```

**Comment by mds1** [comment]
Done, thanks!
