### ISSUE TITLE
Deploy Multicall3 to Arthera Mainnet

### ISSUE THREAD

**Issue by bertux** [mds1/multicall#258]
### Chain Name

Arthera Mainnet

### Chain ID

10242

### RPC URL

https://rpc.arthera.net

### Block Explorer URL

https://explorer.arthera.net/

### Deployment Funds

Yes

**Comment by bertux** [comment]
For the deployment funds I've sent a gas subscription as I've used to deploy and publish at https://explorer.arthera.net/address/0xE0FE85451FD9d9a66BEB91f162c2b43a5148D296?tab=contract
To make integrations easier I would prefer to have it deployed at the same address than other blockchains.

**Comment by mds1** [comment]
Done, thanks!
