### ISSUE TITLE
Deploy Multicall3 to Arthera Testnet

### ISSUE THREAD

**Issue by bertux** [mds1/multicall#259]
### Chain Name

Arthera Testnet

### Chain ID

10243

### RPC URL

https://rpc-test.arthera.net/

### Block Explorer URL

https://explorer-test.arthera.net/

### Deployment Funds

Yes

**Comment by bertux** [comment]
Since #112 the testnet has been replaced by the same version than mainnet.
So as for #258 for the deployment funds I've sent a gas subscription as I've used to deploy and publish at https://explorer-test.arthera.net/address/0x99812bfD7B7D1bF68c62A999301338FfF4Acf737?tab=contract
To make integrations easier I would prefer to have it deployed at the same address than other blockchains.

**Comment by mds1** [comment]
Done, thanks!
