### ISSUE TITLE
Adicionar red

### ISSUE THREAD

**Issue by socarrandinn** [mds1/multicall#262]
### Chain Name

Genesys Mainnet

### Chain ID

16507

### RPC URL

https://rpc.genesys.network

### Block Explorer URL

https://gchainexplorer.genesys.network:443

### Deployment Funds

Yes

**Comment by mds1** [comment]
Can you provide another RPC URL? This one does not seem to work. Additionally, the deployer account `0x05f32B3cC3888453ff71B01135B34FF8e41263F2` has no balance, but it says deployment funds were sent

```
$ cast balance 0x05f32B3cC3888453ff71B01135B34FF8e41263F2 -r https://gchainexplorer.genesys.network:443
Error:
deserialization error: expected value at line 1 column 1

Context:
- expected value at line 1 column 1
```

**Comment by mds1** [comment]
Closing as stale due to no reply
