### ISSUE TITLE
Deploy multicall3 on Taiko mainnet

### ISSUE THREAD

**Issue by dantaik** [mds1/multicall#266]
Please deploy to deploy it on May 28th, 2024.

### Chain Name

Taiko Mainnet

### Chain ID

167000

### RPC URL

rpc.mainnet.taiko.xyz (NOT LIVE YET)

### Block Explorer URL

- taikoscan.io
- taikoscan.network
- https://taiko.socialscan.io/

### Deployment Funds

Yes - https://etherscan.io/tx/0x7d293c643ea4dfea34285e89489f9147366b60efc7f77958c794ce071afd0088

**Comment by mds1** [comment]
Can you let me know once that RPC is live? Just tested and seems to not be live yet
```
$ cast chain-id -r https://rpc.mainnet.taiko.xyz
Error:
error sending request for url (https://rpc.mainnet.taiko.xyz/)

Context:
- Error #0: error sending request for url (https://rpc.mainnet.taiko.xyz/)
- Error #1: client error (Connect)
- Error #2: dns error: failed to lookup address information: nodename nor servname provided, or not known
- Error #3: failed to lookup address information: nodename nor servname provided, or not known
```

**Comment by dantaik** [comment]
> Can you let me know once that RPC is live? Just tested and seems to not be live yet
> 
> ```
> $ cast chain-id -r https://rpc.mainnet.taiko.xyz
> Error:
> error sending request for url (https://rpc.mainnet.taiko.xyz/)
> 
> Context:
> - Error #0: error sending request for url (https://rpc.mainnet.taiko.xyz/)
> - Error #1: client error (Connect)
> - Error #2: dns error: failed to lookup address information: nodename nor servname provided, or not known
> - Error #3: failed to lookup address information: nodename nor servname provided, or not known
> ```

Will do  @mds1

**Comment by mds1** [comment]
Thanks! Can you send the deployments funds on Taiko mainnet? This way I don't have to bridge funds, which causes a nonce bump on some chains. Sorry that was not clear.

Feel free to DM me on telegram at msolomon4 to discuss more, so it's a bit faster than github :)

**Comment by dantaik** [comment]
https://taikoscan.io/tx/0xbec91dd79c57bbf2ab8b0ad825d59d4f99ad99749b6a687f412767a5b557d4f9

0.1ETH sent on Taiko to you.

**Comment by mds1** [comment]
Hi @dantaik, can you please DM me on telegram?

**Comment by dantaik** [comment]
> msolomon4

I cannot due to an error. Could you please DM me (@dantaik) instead?

**Comment by dantaik** [comment]
Our engineer has  deployed a copy at `0x174EB72C7d94a6D7dBAE3e4d20337B57088bB246`. Thank you.

**Comment by mds1** [comment]
Done, thanks!
