### ISSUE TITLE
Deploy Multicall3 on SEI EVM Mainnet

### ISSUE THREAD

**Issue by tiagofilipenunes** [mds1/multicall#269]
### Chain Name

Sei Network

### Chain ID

1329

### RPC URL

https://evm-rpc.sei-apis.com

### Block Explorer URL

https://seitrace.com

### Deployment Funds

Yes

**Comment by tiagofilipenunes** [comment]
@mds1 

There is a PR to add the Sei Network mainnet EVM chain to ethereum-lists:

https://github.com/ethereum-lists/chains/pull/5157

Thanks!

**Comment by mds1** [comment]
Done, thanks!
