### ISSUE TITLE
Add support for Lisk Mainnet 

### ISSUE THREAD

**Issue by densmirnov** [mds1/multicall#273]
### Chain Name

Lisk Mainnet

### Chain ID

1135

### RPC URL

https://blockscout.lisk.com

### Block Explorer URL

https://blockscout.lisk.com

### Deployment Funds

No

**Comment by mds1** [comment]
It is already deploy on Lisk: https://blockscout.lisk.com/address/0xcA11bde05977b3631167028862bE2a173976CA11?tab=contract
