### ISSUE TITLE
Request to deploy Multicall3 on OX Chain

### ISSUE THREAD

**Issue by Leonchen6666** [mds1/multicall#276]
### Chain Name

OX Chain

### Chain ID

6699

### RPC URL

https://rpc-ox-chain-2s86s7wp21.t.conduit.xyz

### Block Explorer URL

https://explorer-ox-chain-2s86s7wp21.t.conduit.xyz

### Deployment Funds

Yes

**Comment by mds1** [comment]
Done, thanks!
