### ISSUE TITLE
Reqeust to deploy Multicall3 on BOX Chain ( OX Chain testnet )

### ISSUE THREAD

**Issue by Leonchen6666** [mds1/multicall#277]
### Chain Name

BOX Chain

### Chain ID

42299

### RPC URL

https://rpc-boxchain-t4zoh9y5dr.t.conduit.xyz

### Block Explorer URL

https://explorerl2new-boxchain-t4zoh9y5dr.t.conduit.xyz

### Deployment Funds

Yes

**Comment by mds1** [comment]
Done, thanks!
