### ISSUE TITLE
Request Deployment For Camp Network

### ISSUE THREAD

**Issue by charlenenicer** [mds1/multicall#280]
### Chain Name

Camp Network Testnet V2

### Chain ID

325000

### RPC URL

https://rpc.camp-network-testnet.gelato.digital

### Block Explorer URL

https://camp-network-testnet.blockscout.com

### Deployment Funds

Yes

**Comment by mds1** [comment]
When I try sending a transaction on this chain I get a JSON RPC error: `TransactionsController: Can only call updateEditableParams on an unapproved transaction`. I have not seen this before, do you know the cause of this error?

**Comment by mds1** [comment]
Closing as stale
