### ISSUE TITLE
Chiliz Testnet Deployment Request

### ISSUE THREAD

**Issue by izhao-cube** [mds1/multicall#281]
### Chain Name

Chiliz Spicy Testnet

### Chain ID

88882

### RPC URL

https://spicy-rpc.chiliz.com/

### Block Explorer URL

https://testnet.chiliscan.com/

### Deployment Funds

Yes

**Comment by mds1** [comment]
The deployer balance is 3 CHZ, but it says I need 7.503 CHZ to deploy. I would suggest funding the deployer with at least 8-10 CHZ total to protect against gas price fluctuations

**Comment by mds1** [comment]
Done, thanks!
