### ISSUE TITLE
Add support for Cronos zkEVM Testnet

### ISSUE THREAD

**Issue by zillarelli** [mds1/multicall#286]
### Chain Name

Cronos zkEVM Testnet

### Chain ID

282

### RPC URL

https://testnet.zkevm.cronos.org

### Block Explorer URL

https://explorer.zkevm.cronos.org/testnet

### Deployment Funds

Yes

**Comment by mds1** [comment]
Since this is a zkEVM, can you confirm (or point to docs) that confirms that address derivation is the same as on Ethereum? I want to verify that deploying with nonce 0 will give the expected address

**Comment by zillarelli** [comment]
I am not sure where that exact info is, but I'm hoping it is in these official developer docs: https://docs-zkevm.cronos.org/for-developers/resources-for-developers

**Comment by 0xartcro** [comment]
Asked Cronos team member, let's hope he answers :)

https://x.com/0xArtCro/status/1824227575889035460

**Comment by mds1** [comment]
Closing until we know this answer
