### ISSUE TITLE
Add support for Boba BNB Mainnet

### ISSUE THREAD

**Issue by whhsw** [mds1/multicall#287]
### Chain Name

Boba BNB Mainnet

### Chain ID

56288

### RPC URL

https://bnb.boba.network

### Block Explorer URL

https://bnb.bobascan.com/

### Deployment Funds

No

**Comment by nikicat** [comment]
Hello, why is it not planned?

**Comment by nikicat** [comment]
Btw Multicall3 [is already deployed](https://bnb.bobascan.com/address/0x2A12e278B704e5A0b4bF8A9F7e93dFe8a24CD9c6/contract/56288/code)

**Comment by whhsw** [comment]
thanks for this update. I guess it's cuz this chain is rarely used?

> Btw Multicall3 [is already deployed](https://bnb.bobascan.com/address/0x2A12e278B704e5A0b4bF8A9F7e93dFe8a24CD9c6/contract/56288/code)
