### ISSUE TITLE
Add support for Plume Testnet

### ISSUE THREAD

**Issue by eyqs** [mds1/multicall#288]
### Chain Name

Plume Testnet

### Chain ID

161221135

### RPC URL

https://testnet-rpc.plumenetwork.xyz/http

### Block Explorer URL

https://testnet-explorer.plumenetwork.xyz/

### Deployment Funds

Yes

**Comment by eyqs** [comment]
We are an Arbitrum Orbit chain so we cannot deploy with the presigned transaction. I made sure not to try, so nonce 0 should still be available.

**Comment by mds1** [comment]
Done, thanks!
