### ISSUE TITLE
Add support for Yominet (Kamigotchi game L2)

### ISSUE THREAD

**Issue by plotchy** [mds1/multicall#294]
### Chain Name

Yominet

### Chain ID

5264468217

### RPC URL

https://yominet.rpc.caldera.xyz/http

### Block Explorer URL

https://yominet.explorer.caldera.xyz

### Deployment Funds

Yes

**Comment by mds1** [comment]
Oh hey @plotchy, nice to see you here! 

I'll be doing the next batch of deployments this week :)

**Comment by mds1** [comment]
Done, thanks!
