### ISSUE TITLE
Add support for Gravity

### ISSUE THREAD

**Issue by myz1237** [mds1/multicall#296]
### Chain Name

Gravity Alpha Mainnet

### Chain ID

1625

### RPC URL

https://rpc.gravity.xyz

### Block Explorer URL

https://explorer.gravity.xyz/

### Deployment Funds

Yes

**Comment by myz1237** [comment]
Funded

**Comment by mds1** [comment]
Done, thanks!

**Comment by myz1237** [comment]
Thanks a lot!
