### ISSUE TITLE
Add support for Ethereum PoW, DIS CHAIN, Mixin Virtual Machine, OctaSpace, BOB, Dymension, zkLink Nova, BounceBit, Endurance Smart Chain

### ISSUE THREAD

**Issue by qwang1113** [mds1/multicall#297]
### Chain Name

Ethereum PoW, DIS CHAIN, Mixin Virtual Machine, OctaSpace, BOB, Dymension, zkLink Nova, BounceBit, Endurance Smart Chain

### Chain ID

Ethereum PoW=10001, DIS CHAIN=513100, Mixin Virtual Machine=73927, OctaSpace=800001, BOB=60808, Dymension=1100, zkLink Nova=810180, BounceBit=6001, Endurance=648

### RPC URL

Ethereum PoW=https://mainnet.ethereumpow.org, DIS CHAIN=https://rpc.dischain.xyz, Mixin Virtual Machine=https://geth.mvm.dev, OctaSpace=https://rpc.octa.space, BOB=https://rpc.gobob.xyz, Dymension=https://jsonrpc.dymension.nodestake.org, zkLink Nova=https://rpc.zklink.io, BounceBit=https://fullnode-mainnet.bouncebitapi.com, Endurance=https://rpc-endurance.fusionist.io

### Block Explorer URL

Ethereum PoW=https://www.oklink.com/ethw/, DIS CHAIN=https://www.oklink.com/dis, Mixin Virtual Machine=https://scan.mvm.dev, OctaSpace=https://explorer.octa.space, BOB=https://explorer.gobob.xyz, Dymension=https://dym.fyi, zkLink Nova=https://explorer.zklink.io, BounceBit=https://bbscan.io, Endurance=https://explorer.endurance.fusionist.io

### Deployment Funds

Yes

**Comment by qwang1113** [comment]
- Mixin Virtual Machine
- Dymension
- Endurance

Except for the above networks, which have not been transferred to deployment costs, all other networks have been transferred.

@mds1

**Comment by mds1** [comment]
Can you open one issue per chain for tracking purposes? There's a lot in here, some of which are zk and may not be EVM compatible. I have a backlog of chains to deploy and one per issue would make things much easier for me :)
