### ISSUE TITLE
Deploy on Cronos zkEVM Mainnet

### ISSUE THREAD

**Issue by mr-kenikh** [mds1/multicall#298]
### Chain Name

Cronos zkEVM

### Chain ID

388

### RPC URL

https://mainnet.zkevm.cronos.org

### Block Explorer URL

https://explorer.zkevm.cronos.org

### Deployment Funds

Yes

**Comment by mds1** [comment]
Is the Cronos zkEVM address equivalent to Ethereum Mainnet, i.e. when deploying from an account nonce 0, do you get the same address as you would on Ethereum?

**Comment by mr-kenikh** [comment]
@mds1 deploying from an account nonce 0 gives me different address than on Ethereum 🙄
