### ISSUE TITLE
Deploy on Tron Shasta

### ISSUE THREAD

**Issue by Metaxona** [mds1/multicall#300]
### Chain Name

Tron Shasta

### Chain ID

2494104990

### RPC URL

https://api.shasta.trongrid.io

### Block Explorer URL

https://shasta.tronscan.org/

### Deployment Funds

No

**Comment by mds1** [comment]
Tron addresses are not EVM compatible so I am going to close this issue, as I do not want to use up the nonce in case it becomes EVM compatible
