### ISSUE TITLE
Deployment Request: Camp Network Testnet V2

### ISSUE THREAD

**Issue by saurabh** [mds1/multicall#309]
### Chain Name

Camp Network Testnet V2

### Chain ID

325000

### RPC URL

https://rpc-campnetwork.xyz

### Block Explorer URL

https://camp-network-testnet.blockscout.com

### Deployment Funds

Yes

**Comment by mds1** [comment]
Looks like this is an OP Stack fork, so it's already there as a [preinstall](https://specs.optimism.io/protocol/preinstalls.html): https://camp-network-testnet.blockscout.com/address/0xcA11bde05977b3631167028862bE2a173976CA11?tab=contract
