### ISSUE TITLE
World Chain

### ISSUE THREAD

**Issue by BioMark3r** [mds1/multicall#315]
### Chain Name

World Chain

### Chain ID

480

### RPC URL

https://worldchain-mainnet.g.alchemy.com/public

### Block Explorer URL

https://worldchain-mainnet.explorer.alchemy.com/

### Deployment Funds

No

**Comment by mds1** [comment]
Since this is an OP Stack chain, Multicall3 is already present as a preinstall :) 
- https://worldchain-mainnet.explorer.alchemy.com/address/0xcA11bde05977b3631167028862bE2a173976CA11?tab=contract
- https://specs.optimism.io/protocol/preinstalls.html
