### ISSUE TITLE
Deployment Request: Viction Mainnet

### ISSUE THREAD

**Issue by tungng98** [mds1/multicall#317]
### Chain Name

Viction Mainnet

### Chain ID

88

### RPC URL

https://rpc.viction.xyz

### Block Explorer URL

https://www.vicscan.xyz

### Deployment Funds

Yes

**Comment by tungng98** [comment]
Hi mds1,

I need your help on Mainnet too. The situation is same as #316.

Thanks.

**Comment by mds1** [comment]
I am getting RPC errors and am unable to generate the transaction: `too many arguments, want at most 1`. This occurs when using the same process I always use for deploys, which is to deploy through Remix 😅

**Comment by tungng98** [comment]
The `too many arguments, want at most 1` error is fixed on Viction Mainnet RPC.

**Comment by mds1** [comment]
Done, thanks!
