### ISSUE TITLE
Deploy to Godwoken Testnet

### ISSUE THREAD

**Issue by Kuzirashi** [mds1/multicall#32]
Please deploy Multicall v3 to Godwoken Testnet (https://chainlist.org/chain/71401).

Funds have been sent already to: 0x05f32B3cC3888453ff71B01135B34FF8e41263F2.

RPC: https://godwoken-testnet-v1.ckbapp.dev/

Block explorers: 
- https://v1.betanet.gwscan.com/
- https://gw-explorer.nervosdao.community/ (Blockscout)

More docs if needed: https://startwithnervos.com/godwoken

cc @mds1

**Comment by mds1** [comment]
Done, thanks!
