### ISSUE TITLE
Deploy Multicall to Flow(EVM) Testnet

### ISSUE THREAD

**Issue by btspoony** [mds1/multicall#321]
### Chain Name

Flow Testnet

### Chain ID

545

### RPC URL

https://testnet.evm.nodes.onflow.org

### Block Explorer URL

https://evm-testnet.flowscan.io

### Deployment Funds

Yes

**Comment by mds1** [comment]
Multicall3 is already on this chain: https://evm-testnet.flowscan.io/address/0xcA11bde05977b3631167028862bE2a173976CA11?tab=contract
