### ISSUE TITLE
Add support for Plume Mainnet

### ISSUE THREAD

**Issue by eyqs** [mds1/multicall#325]
Note that Plume is an Arbitrum Orbit chain, so multicall can't be deployed using the pre-signed transaction because the gas limit is too low.

### Chain Name

Plume Mainnet

### Chain ID

98865

### RPC URL

https://rpc.plumenetwork.xyz/

### Block Explorer URL

https://phoenix-explorer.plumenetwork.xyz

### Deployment Funds

Yes

**Comment by mds1** [comment]
Do you have another RPC URL? The provided one does not work

**Comment by eyqs** [comment]
Updated the RPC URL! Sorry about the churn.

**Comment by eyqs** [comment]
Hey @mds1 - any updates on this? `0x1E91557322053858cf75cFE5b2d030D27cb2cA8D` has 0.1 ETH on the provided RPC URL.

**Comment by mds1** [comment]
Done, thanks!
