### ISSUE TITLE
Deployment Request on WEMIX3.0

### ISSUE THREAD

**Issue by egonspace** [mds1/multicall#329]
### Chain Name

WEMIX3.0 Mainnet

### Chain ID

1111

### RPC URL

https://api.wemix.com

### Block Explorer URL

https://wemixscan.com (please set the gas price to 101Gwei)

### Deployment Funds

Yes

Or please give me the signed tx with 101Gwei gasprice

**Comment by mds1** [comment]
Do I need to use 101 gwei for the base fee or the priority fee, or both? When I tried sending a transaction with the defaults I received a JSON RPC error

**Comment by egonspace** [comment]
Thank you for your trying. You should set 1wei+ for the base fee and 100 Gwei for the priority fee. So you can set 101 Gwei for the gas price.

**Comment by egonspace** [comment]
Hi, did you try it? If you have a problem with those gas configuration, please let me know that.

**Comment by mds1** [comment]
Done, thanks!
