### ISSUE TITLE
Add support for Aleph Zero EVM Mainnet

### ISSUE THREAD

**Issue by piotrMocz** [mds1/multicall#332]
Note: Aleph Zero EVM is an Arbitrum Orbit chain, so it wasn't possible to use the pre-signed transaction.

### Chain Name

Aleph Zero EVM

### Chain ID

41455

### RPC URL

https://rpc.alephzero.raas.gelato.cloud

### Block Explorer URL

https://evm-explorer.alephzero.org/

### Deployment Funds

Yes
Note: the chain uses a custom gas token (AZERO), which was sent to the deployer preparation account (700AZERO, which is slightly more than 0.1ETH).

**Comment by mds1** [comment]
Done, thanks! If you want the excess funds refunded (>699 AZERO) please let me know an address to refund it to

**Comment by piotrMocz** [comment]
@mds1 thank you! The address is `0xE3707375B9a7D450F282c3D51bCC0519A1D55E17`
