### ISSUE TITLE
Ancient8

### ISSUE THREAD

**Issue by mewwts** [mds1/multicall#336]
### Chain Name

Ancient8

### Chain ID

888888888

### RPC URL

https://rpc.ancient8.gg

### Block Explorer URL

https://scan.ancient8.gg/

### Deployment Funds

No

**Comment by mds1** [comment]
As you can see in the README update I just pushed, the Multicall3 deployer key has been compromised, and someone used it to deploy a different contract on Ancient8: https://scan.ancient8.gg/address/0xcA11bde05977b3631167028862bE2a173976CA11

As a result, the regular Multicall3 contract cannot be deployed at this address. You may consider asking the chain operator to place Multicall3 as a predeploy on this chain to overwrite the existing code. Ancient8 is an OP Stack chain, and new OP Stack chains do include Multicall3 as a [preinstall](https://specs.optimism.io/protocol/preinstalls.html) by default, so they may be willing to overwrite the code in a hard fork.
