### ISSUE TITLE
Refund coins

### ISSUE THREAD

**Issue by 123Nurul-cloud** [mds1/multicall#340]
### Chain Name

123Nurul-cloud

### Chain ID

25

### RPC URL

0x0db606b302a929c8371cd795c054852e44a990d293833b982958de864167cb94

### Block Explorer URL

0xF30e24FB92F6D54d6972B3179549F85D37D6BDB2

### Deployment Funds

Yes

**Comment by 123Nurul-cloud** [comment]
I want to refund my coin tu wld

**Comment by mds1** [comment]
I do not know what is being requested here, so am closing this issue. If you accidentally sent funds and need them refunded please let me know the chain details
