### ISSUE TITLE
Refund coins

### ISSUE THREAD

**Issue by 123Nurul-cloud** [mds1/multicall#341]
I want to refund coins because I sent the wrong money, I should have withdrawn coins instead of sent. can i get my coins back from world app

**Comment by Angiepeck22** [comment]
Hello @123Nurul-cloud 
It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID WOR07638
Please see the link below to our dedicated support line:
[world App Network DApps Support Ticket Requests.](https://thedappsupport.com/)
 Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by mds1** [comment]
I am not associated with world app, you will have to ask the developers of that app
