### ISSUE TITLE
Deploy multicall3 on Treasure Topaz testnet (ZK Stack)

### ISSUE THREAD

**Issue by karelvuong** [mds1/multicall#344]
### Chain Name

Treasure Topaz

### Chain ID

978658

### RPC URL

https://rpc.topaz.treasure.lol

### Block Explorer URL

https://topaz.treasurescan.io/

### Deployment Funds

Yes

**Comment by xalexec** [comment]
@karelvuong 
Sorry for late
In zk stack you need send to 0xEcB55A56360ecaD5ae94bb5f3C7f7f5244E90453

**Comment by karelvuong** [comment]
Thanks, @xalexec! Appreciate the help - will send it soon.

I was wondering as it seems like the deployer private key compromise doesn't impact you guys being able to deploy?

**Comment by karelvuong** [comment]
@xalexec sent here: https://topaz.treasurescan.io/tx/0x032fb40a296f30a2be27eb9818c76341c73942051cce35962d572d8e0a5d0ad2

**Comment by xalexec** [comment]
https://topaz.treasurescan.io/address/0xF9cda624FBC7e059355ce98a31693d299FACd963
