### ISSUE TITLE
Deploy to Optimism Göerli

### ISSUE THREAD

**Issue by adamazad** [mds1/multicall#36]
Hi, awesome contract! 

From [Optimism docs](https://community.optimism.io/docs/useful-tools/networks/#optimism-kovan-old-testnet):

> **Deprecation notice**
> We are transitioning our test network to Goerli. We expect Optimistic Kovan to exist until August 15th, 2022.

Could you please deploy it to Optimism Göerli? Thank you!

**Comment by mds1** [comment]
Sure thing! Could you send ETH to the deployer account (0x05f32B3cC3888453ff71B01135B34FF8e41263F2) on Optimism Goerli?

**Comment by adamazad** [comment]
Done. Let me know if it's insufficient :)

**Comment by mds1** [comment]
Done, thanks! https://blockscout.com/optimism/goerli/address/0xcA11bde05977b3631167028862bE2a173976CA11/contracts
