### ISSUE TITLE
Deploy to Arbitrum Görli

### ISSUE THREAD

**Issue by adamazad** [mds1/multicall#38]
I have already sent 0.01 ETH to 0x05f32B3cC3888453ff71B01135B34FF8e41263F2 :)

- ChainID 421613
- RPC URL at https://goerli-rollup.arbitrum.io/rpc
- Explorer https://goerli-rollup-explorer.arbitrum.io/

Thank you!

**Comment by mds1** [comment]
Hey, sorry I've been out the last week, I'll get to this sometime this week 🙂

**Comment by mds1** [comment]
Done! https://goerli-rollup-explorer.arbitrum.io/address/0xcA11bde05977b3631167028862bE2a173976CA11/contracts
