### ISSUE TITLE
`estimateGas` using `gasleft()`

### ISSUE THREAD

**Issue by sebastiantf** [mds1/multicall#39]
Would it be possible to add another utility function equivalent to do multiple `eth_estimateGas` with some `gasleft()` magic ✨ 

Guess its too hard to get it right

**Comment by mds1** [comment]
Sorry what exactly do you mean here? `eth_estimateGas` is an off-chain RPC call so I don't quite understand the question 😅

**Comment by sebastiantf** [comment]
Apologies for the confusion. I meant a function that can be used to estimate gas for multiple transactions in a single call, that returns those estimates separately for each call.

Similar to `aggregate()`, but only the return values would be gas usage, instead of actual call results

**Comment by mds1** [comment]
In theory you could, but it won't be very accurate or useful—the sum of the individual call gas estimates won't equal the aggregated call gas limit / gas usage for various reasons. Gas costs vary by a lot of factors cold/warm addresses, cold/warm storage slots, different refund amounts based on total gas usage, etc. 

What is your use case for needing estimates of individual calls if they are going to be submitted together via something like `aggregate`?

**Comment by sebastiantf** [comment]
Yeah, it wont be accurate. The use case is to just be able to make multiple `estimateGas`s in a single RPC call. And the individual calls are not exactly going to be submitted together, but separately. Yes, that does cause the gas costs to vary very much. But just wondering if its still possible to get close to it and since Multicall is already a public good with very useful utility functions, something like this would also belong here.

**Comment by mds1** [comment]
The JSON-RPC spec supports batching, so you can batch multiple individual `eth_estimateGas` calls into a single request, which it sounds like is exactly what you want 
- https://www.jsonrpc.org/specification#batch
- https://geth.ethereum.org/docs/rpc/batch

**Comment by sebastiantf** [comment]
Yes, but I had seen Alchemy documentation recommending against it here:
- https://docs.alchemy.com/reference/batch-requests#when-should-i-use-batch-requests
And I believe it also adds to the CUs and pushes the rate limits -- preventing of which is another advantage of batching them

**Comment by sebastiantf** [comment]
But I guess JSON RPC batching is the best bet among the options

**Comment by mds1** [comment]
Yea either batch or individual txs is probably your best bet. Gas estimation can get tricky and I don't think solving it at the contract level is too useful / the right solution. It will also simply not work for a lot cases, such as when a call needs to come from a certain sender. 

The nodes use a binary search to find the gas limit so the tx gets executed many times, so does make sense if it's pricey in terms of CUs unfortunately 😕

**Comment by sebastiantf** [comment]
JSON RPC batching is very inefficient if aiming for performance/speed: https://github.com/ethers-io/ethers.js/issues/62#issuecomment-382444315

Apparently JSON RPC batching executes the requests are performed serially. 
I tried it out, and multiple concurrent requests are way faster than batching
