### ISSUE TITLE
Deployment of MulticallV3 to Flare's Coston2 network

### ISSUE THREAD

**Issue by alexdupre** [mds1/multicall#40]
Please deploy MulticallV3 on the 2nd test network of Flare.
I've sent you 1 C2FLR to pay for deploy costs, you can set 25 gwei as gas price and no priority fee.

| Chain | Explorer | Funds sent | Transaction |
| --- | --- | --- | --- |
| Coston2 |  https://coston2-explorer.flare.network/ | 1 C2FLR | [Link to explorer](https://coston2-explorer.flare.network/tx/0xae8eb3dcf89a47ff012462dfdb9c652765e5533d8de08fdd0ba00881ee34d9ed/internal-transactions) |

**Comment by mds1** [comment]
Thanks @alexdupre, can you provide an RPC URL and chain ID for Coston2? I searched https://chainlist.org/ but don't see it there

**Comment by alexdupre** [comment]
RPC URL: https://coston2-api.flare.network/ext/C/rpc

ChainId: 114

**Comment by mds1** [comment]
Done, thanks! https://coston2-explorer.flare.network/address/0xcA11bde05977b3631167028862bE2a173976CA11/contracts
