### ISSUE TITLE
Feat: add Velas Chain

### ISSUE THREAD

**Issue by maxklenk** [mds1/multicall#41]
Chain Name: Velas
Chain Id: 106
Chain Details: https://chainlist.org/chain/106
Explorer: https://evmexplorer.velas.com/
RPC: https://evmexplorer.velas.com/rpc
Deployer Wallet filled: https://evmexplorer.velas.com/address/0x05f32B3cC3888453ff71B01135B34FF8e41263F2

**Comment by mds1** [comment]
Done, thanks! https://evmexplorer.velas.com/address/0xcA11bde05977b3631167028862bE2a173976CA11/contracts
