### ISSUE TITLE
Can i get the address for pulsechain?

### ISSUE THREAD

**Issue by Geek1216** [mds1/multicall#43]

**Comment by mds1** [comment]
It's not yet deployed to pulsechain, but if send funds to 0x05f32B3cC3888453ff71B01135B34FF8e41263F2 for deployment, I can deploy it there 🙂

**Comment by Geek1216** [comment]
I have deployed it myself lol :)

**Comment by mds1** [comment]
Actually it looks like I deployed it to pulsechain 8 months ago, assuming this is the correct block explorer? https://scan.v2b.testnet.pulsechain.com/address/0xcA11bde05977b3631167028862bE2a173976CA11/transactions

Wondering if I just never added pulsechain to the README, or if they just rebranded?

**Comment by 3commascapital** [comment]
pulsechain is simply a fork of ethereum, so this contract, so long as it is deployed before the fork block, will come along for the ride 🎉

**Comment by mds1** [comment]
Ahh got it, thanks! Can you link me to the current pulsechain explorer(s) for all chains that did this (e.g. mainnet and testnets) and I'll add them to the readme? Seems the above link is dead

**Comment by 3commascapital** [comment]
https://scan.v4.testnet.pulsechain.com/address/0xcA11bde05977b3631167028862bE2a173976CA11/transactions
mainnet will be
https://scan.pulsechain.com/address/0xcA11bde05977b3631167028862bE2a173976CA11/transactions

**Comment by mds1** [comment]
Ah I see, thanks!
