### ISSUE TITLE
Deploy Multicall3 on Celo Alfajores testnet

### ISSUE THREAD

**Issue by jeanregisser** [mds1/multicall#45]
Hi,

Could you also deploy the Multicall3 contract on the Celo Alfajores testnet?

Website: https://docs.celo.org/network
Explorer: https://explorer.celo.org/alfajores
Chain ID: 44787

I already funded the deployer account.

Thanks 🙏

**Comment by mds1** [comment]
Done, thanks! https://explorer.celo.org/mainnet/address/0xcA11bde05977b3631167028862bE2a173976CA11/contracts
