### ISSUE TITLE
Deployment of MulticallV3 to Flare Mainnet

### ISSUE THREAD

**Issue by alexdupre** [mds1/multicall#46]
Please deploy MulticallV3 on the Flare Mainnet.
I've sent you 0.5 FLR to pay for deploy costs, you can set 25 gwei as gas price and no priority fee.

| Chain | ChainId | RPC endpoint | Explorer | Funds sent | Transaction |
| --- | --- | --- | --- | --- | --- |
| Flare Mainnet | 14 | https://flare-api.flare.network/ext/C/rpc | https://flare-explorer.flare.network/ | 0.5 FLR | [Link to explorer](https://flare-explorer.flare.network/tx/0x854d71141c9f8e12294bd8da3ef6ff527a7018b623c0f005123e8b9aa66ed2d8) |

**Comment by mds1** [comment]
Done, thank you!
