### ISSUE TITLE
Deploy multicall v3 in private chain with the same address.

### ISSUE THREAD

**Issue by noyyyy** [mds1/multicall#48]
We have a private chain for internal testing and I want to use the multicall contract with the same address. It's possible if it's deployed with create2 with specific args. Could we achieve it?

**Comment by mds1** [comment]
You'll have to place the Multicall3 bytecode at the specified address manually, since you can't deploy it without the deployer's private key. I'm not sure of the specifics of your chain, but something like anvil, hardhat, or tenderly all support this

**Comment by mds1** [comment]
A create2 factory wasn't used here because there is no create2 factory at the same address on 50+ chains. So you still have the same problem of getting that create2 factory at the same address on each chain, including your private chain

**Comment by noyyyy** [comment]
> A create2 factory wasn't used here because there is no create2 factory at the same address on 50+ chains. So you still have the same problem of getting that create2 factory at the same address on each chain, including your private chain

It doesn't matter if the create2 factory address is different. Once the input args of create2 are deterministic(mainly contract bytes code), the outcome address will be the same.

**Comment by mds1** [comment]
> It doesn't matter if the create2 factory address is the same. Once the input args of create2 are deterministic(mainly contract bytes code), the outcome address will be the same.

This is incorrect, the deployer address (the create2 factory) is a factor in the resulting contract address. From [EIP-1014](https://eips.ethereum.org/EIPS/eip-1014):

>  Behaves identically to `CREATE` (`0xf0`), except using `keccak256( 0xff ++ address ++ salt ++ keccak256(init_code))[12:]` instead of the usual sender-and-nonce-hash as the address where the contract is initialized at.

Where `address` is the address of the contract using the CREATE2 opcode 🙂

**Comment by mds1** [comment]
No worries, will close this now 👌
