### ISSUE TITLE
Examples in the README

### ISSUE THREAD

**Issue by PaulRBerg** [mds1/multicall#52]
Hey Matt, thanks for building this. I just started playing with it today, and it's awesome.

I was wondering if you know of any good example repositories that could be included in the README? I think that it would be helpful to provide some - for instance, a repo that uses multicall to query the token balances of multiple addresses is probably a common use case.

**Comment by mds1** [comment]
Good idea, I can definitely link to some example usages in the readme, since it will vary by language/tooling. For example, ethers-rs has a built in `Multicall` struct that uses Multicall3, wagmi has a `multicall` method and `readContracts` method that uses it too. There's definitely also some code snippets I know that use it directly in TS/python

If you let me know what language/tooling you are interested in I can find a snippet. Searching sourcegraph for the contract address is another good way to find example usages

**Comment by paulrberg** [comment]
Awesome.

To be fair, you went above and beyond what I had in mind - I was mainly interested in a few Solidity examples (even just code snippets), but now that I think about it, some examples from across the Ethereum developer ecosystem would also be helpful.

I wrote this function, which I think might be worth adding to the README - and maybe also in `forge-std` as an util?

```solidity
/// @dev Performs a single call with Multicall3 to query the ERC-20 token balances of the given addresses.
function getTokenBalances(address[] addresses) internal view returns (uint256[] balances) {
    uint256 length = addresses.length;
    Call[] memory calls = new Call[](length);
    for (uint256 i = 0; i < length; ) {
        calls[i] = Call({ target: address(token), callData: abi.encodeCall(IERC20.balanceOf, (addresses[i])) });
        unchecked {
            ++i;
        }
    }
    (, bytes[] memory returnData) = multicall.aggregate(calls);
    balances = abi.decode(returnData, (uint256[]));
}
```

**Comment by dhamoui** [comment]
Hey @mds1 ,

Just chiming in that some python examples/snippets would be much appreciated. I gave it a shot myself below, but I'm running into errors.

```
from web3 import Web3
from utils import helper_funcs
import os

# Set up Web3 connection to Ethereum node
web3 = Web3(Web3.HTTPProvider("<polygon-mainnet-rpc-url>"))

# Define contract address and function signatures
multicall_address = Web3.toChecksumAddress('0xcA11bde05977b3631167028862bE2a173976CA11') # Multicall3
oracle_address = Web3.toChecksumAddress('0xb023e699F5a33916Ea823A16485e259257cA8Bd1') # [Aave V3 Oracle](https://polygonscan.com/address/0xb023e699F5a33916Ea823A16485e259257cA8Bd1)

oracle_abi = helper_funcs.read_abi("./abis/oracle.abi")
oracle = web3.eth.contract(address=oracle_address, abi=oracle_abi)

# Define list of addresses to get prices for
addresses = ['0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270', '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174'] #MATIC and USDC

# Encode function calls for each address
calls = []
for address in addresses:
    address = Web3.toChecksumAddress(address)
    call_data = oracle.encodeABI(fn_name="getAssetPrice", args=[address])
    calls.append({'target': multicall_address, 'callData': call_data})

# Call multicall contract to execute all function calls in one transaction
multicall_contract = web3.eth.contract(address=multicall_address, abi=helper_funcs.read_abi("./abis/multicall3.abi"))
result = multicall_contract.functions.aggregate(calls).call()

# Print results
for i, address in enumerate(addresses):
    price = result[1][i]
    print(f"{address}: {price}")
```

Thanks for all your efforts so far.

**Comment by mds1** [comment]
I don't use python for ETH dev often, maybe @fubuloubu can provide a python snippet here which I can include once I add the examples. Pretty sure Multicall3 is integrated into [Ape](https://github.com/ApeWorX/ape), so that might be the best option

**Comment by fubuloubu** [comment]
This is a great example:
https://github.com/ApeWorX/ape/pull/1189#issuecomment-1409357048

**Comment by dhamoui** [comment]
Thanks @mds1, @fubuloubu. Do you know where I can find examples of using multicall to submit transactions? (As opposed to using it for calls like the examples I and @fubuloubu provided)

Asking because I'm able to get the calls working, but I'm having trouble executing transactions. I'm assuming it has to do with the following note in the `README.md`:

> Additionally, make sure you understand how msg.sender works when calling vs. delegatecalling to the Multicall contract

**Comment by fubuloubu** [comment]
> Thanks @mds1, @fubuloubu. Do you know where I can find examples of using multicall to submit transactions? (As opposed to using it for calls like the examples I and @fubuloubu provided)
> 
> Asking because I'm able to get the calls working, but I'm having trouble executing transactions. I'm assuming it has to do with the following note in the `README.md`:
> 
> > Additionally, make sure you understand how msg.sender works when calling vs. delegatecalling to the Multicall contract

Just swap `call = multicall.Call()` for `txn = multicall.Transaction()` and add `sender=signer_account` to the part where you dispatch the call via `receipt = txn(sender=...)`

**Comment by dhamoui** [comment]
Thanks for your suggestion @fubuloubu , but I was hoping to use the base multicall3 contract via web3py along the lines of something like:
`multicall_contract = w3.eth.contract(multicall_address, multicall_abi)`

I've been banging my head for a week now over this and I've tried almost everything yet I can't get the delegation part right. I'm trying to repay a USDC Aave loan, and I can see in the traces that the transaction tries to repay the USDC from the multicall contract as opposed to from my wallet address.

Here is the an example of the trace:
```
UChildAdministrableERC20
.
_transferFrom
(sender = 0xca11bde05977b3631167028862be2a173976ca11, recipient = 0x625e7708f30ca75bfd92586e17077590c60eb4cd, amount = 1000000)
=>
()
```

Here is my script. Any help would be greatly appreciated:
```
from web3 import Web3
from eth_account import Account
from web3.middleware import geth_poa_middleware
from utils import helper_funcs as ut, blockchain as bc
import os
import dotenv

dotenv.load_dotenv()

# Replace these with your own values
infura_url = os.getenv("backup_rpc_url")
private_key = os.getenv("private_key")
wallet_address = os.getenv("wallet_address")

# Initialize web3 instance
w3 = Web3(Web3.HTTPProvider(infura_url))
w3.middleware_onion.inject(geth_poa_middleware, layer=0)

multicall_address = Web3.toChecksumAddress("0xcA11bde05977b3631167028862bE2a173976CA11")
pool_address = Web3.toChecksumAddress("0x794a61358D6845594F94dc1DB02A252b5b4814aD")
erc20_address = Web3.toChecksumAddress("0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174")


# Load Multicall3 ABI
multicall_abi = ut.read_abi('./abis/multicall3.abi')
pool_abi = ut.read_abi('./abis/Pool.abi')
erc20_abi = ut.read_abi('./abis/erc20.abi')

# Create contract object
multicall = w3.eth.contract(address=multicall_address, abi=multicall_abi)
pool = w3.eth.contract(address=pool_address, abi=pool_abi)
erc20 = w3.eth.contract(address=erc20_address, abi=erc20_abi)

amount = 1*(10**6)
# Generate encoded function data for target contracts
approval_call = erc20.functions.approve(pool_address, amount)
#tx_hash, tx_receipt = bc.send_function_call(w3, approval_call, wallet_address, private_key)
#print('Approval Transaction Hash:', tx_hash)
#print('Approval Transaction Receipt:', tx_receipt)

approval_data = erc20.encodeABI(fn_name='approve', args=[pool_address, amount])
func_data1 = pool.encodeABI(fn_name='borrow', args=[erc20_address, amount, 2, 0, wallet_address])
func_data2 = pool.encodeABI(fn_name='repay', args=[erc20_address, amount, 2, wallet_address])

# Aggregate transactions using Multicall3
batched_transactions = [
    #{'target': erc20.address, 'callData': approval_data},
    #{'target': pool.address, 'allowFailure': False, 'callData': func_data1},
    {'target': pool.address, 'allowFailure': False, 'callData': func_data2}
]

# Convert batched_transactions to the proper tuple format
tuple_batched_transactions = [{'target': tx['target'], 'allowFailure': tx['allowFailure'], 'callData': tx['callData']} for tx in batched_transactions]

data = multicall.encodeABI(fn_name='tryAggregate', args=[False, tuple_batched_transactions])
# Sign and send the transaction
nonce = w3.eth.getTransactionCount(wallet_address)
fee_history = w3.eth.fee_history(4, "latest", [10, 90])
baseFeePerGas = fee_history["baseFeePerGas"][0]
maxPriorityFeePerGas = w3.eth.max_priority_fee
transaction = {
    'chainId': 137,
    'to': multicall_address,
    'from': wallet_address,
    'value': 0,
    'gas': 10000000,
    "maxPriorityFeePerGas": maxPriorityFeePerGas,
    "maxFeePerGas": int((2 * baseFeePerGas) + maxPriorityFeePerGas),
    'nonce': nonce,
    'data': data
}

signed_tx = Account.signTransaction(transaction, private_key)
tx_hash = w3.eth.sendRawTransaction(signed_tx.rawTransaction)

# Wait for the transaction receipt
tx_receipt = w3.eth.waitForTransactionReceipt(tx_hash)

print('Transaction Hash:', tx_hash.hex())
print('Transaction Receipt:', tx_receipt)
```

**Comment by fubuloubu** [comment]
Also, if you are making this call from an EOA it likely will not function at all, since you can't do a delegatecall

**Comment by dhamoui** [comment]
Thanks @fubuloubu - no worries at all. Yeah, I'm trying to run this on the Polygon chain which i believe counts as a POA chain(?).

Are you saying that multicall won't work at all on Polygon? If so, why even deploy the contract on the Polygon chain? And I can I use `ape` on the Polygon chain?

Thanks for your time.

**Comment by fubuloubu** [comment]
> Are you saying that multicall won't work at all on Polygon?

No, I'm saying the way you're trying to use multicall won't function on any chain using an EOA wallet. It could work with a smart contract wallet, but those have different ways of making multiple calls sometimes (e.g. Safe)

**Comment by dhamoui** [comment]
@fubuloubu Understood. Thanks very much for the help. I'll give `ape` a shot!

**Comment by mds1** [comment]
Thanks @kfazil! 

Over the next week or two I'm planning to revamp the README/docs and will include examples for various languages/frameworks

**Comment by mds1** [comment]
Closing since the README is now updated with docs/examples
