### ISSUE TITLE
Feat: Deploy Multicall3 to Arbitrum Nova

### ISSUE THREAD

**Issue by chrisco255** [mds1/multicall#56]
Requesting support for Multicall3 on Arbitrum Nova. The block explorer can be found here: https://nova.arbiscan.io/

The chain currently has Multicall2 deployed at: https://nova.arbiscan.io/address/0x5e1eE626420A354BbC9a95FeA1BAd4492e3bcB86

**Comment by mds1** [comment]
Just bridged some funds, will deploy later today once that's done

**Comment by mds1** [comment]
Done! https://nova.arbiscan.io/address/0xcA11bde05977b3631167028862bE2a173976CA11#code

**Comment by chrisco255** [comment]
Thank you!
