### ISSUE TITLE
Deploy Multicall3 to Polygon zkEVM testnet

### ISSUE THREAD

**Issue by oxowl** [mds1/multicall#58]
Requesting support for Multicall3 on Polygon zkEVM testnet. The block explorer can be found here:

ChainID: 1422
Network Name: Polygon zkEVM Testnet 
RPC URL: https://rpc.public.zkevm-test.net/
Currency Symbol: ETH
Block Explorer URL: https://explorer.public.zkevm-test.net/

**Comment by mds1** [comment]
Do you know of a faucet where I can get funds for deployment? Alternatively, if you have some testnet ETH to spare for deployment you can send it to 0x05f32B3cC3888453ff71B01135B34FF8e41263F2

**Comment by mds1** [comment]
Done!
