### ISSUE TITLE
Deploy Multicall3 to DFK Chain

### ISSUE THREAD

**Issue by BisonFutil** [mds1/multicall#59]
Hello,

Here are the info about the chain :

ChainID: 53935
Network Name: DFK Chain
RPC URL:  https://subnets.avax.network/defi-kingdoms/dfk-chain/rpc
Currency Symbol: JEWEL
Block Explorer URL: https://subnets.avax.network/defi-kingdoms

I've sent few JEWEL to the deployer account to cover the deploy.

**Comment by mds1** [comment]
I'm getting the following RPC error:

```
{
  "code": -32000,
  "message": "tx.origin 0x05f32B3cC3888453ff71B01135B34FF8e41263F2 is not authorized to deploy a contract"
}
```

Seems like we need to get that deployer address authorized to deploy a contract? I'm not familiar with DFK Chain so not sure how this works

**Comment by BisonFutil** [comment]
I’ve checked their discord and it seems they might open it up soon on next chain update.
I will check it once it’s done and come back here.

Thanks for your help and work

**Comment by mds1** [comment]
Going to close this for now since there's not currently anything actionable, feel free to reopen once it can be deployed
