### ISSUE TITLE
Deploy to Canto EVM

### ISSUE THREAD

**Issue by agsola** [mds1/multicall#61]
Requesting support for Multicall3 on Canto (and its testnet). Can be found here:

Network Name: CANTO
New RPC URL: https://canto.gravitychain.io/
Chain ID: 7700
Currency Symbol: CANTO
Block Explorer URL: https://evm.explorer.canto.io/

https://docs.canto.io/user-guides/connecting-to-canto

**Comment by mds1** [comment]
By any chance can you send funds to 0x05f32B3cC3888453ff71B01135B34FF8e41263F2 for deployment? I haven't used Canto yet so don't have funds there 🙂

**Comment by mds1** [comment]
Done! https://evm.explorer.canto.io/address/0xcA11bde05977b3631167028862bE2a173976CA11/contracts#address-tabs
