### ISSUE TITLE
Deploy Multicall3 to Step network

### ISSUE THREAD

**Issue by BisonFutil** [mds1/multicall#62]
Hi again :-),

Here are the info about the chain :

ChainID: 1234
Network Name: Step Network
RPC URL: https://rpc.step.network
Currency Symbol: FITFI
Block Explorer URL: https://stepscan.io/

I've transfered FITFI to the deployer account.

**Comment by mds1** [comment]
Done, thank you! https://stepscan.io/address/0xcA11bde05977b3631167028862bE2a173976CA11/contracts#address-tabs
