### ISSUE TITLE
Deploy multicall3

### ISSUE THREAD

**Issue by BisonFutil** [mds1/multicall#63]
Hi, this is a request to deploy multicall3 on two chains. Fee coins have been transfer to the deployer account.

First chain :

ChainID: 4689
Network Name: Iotex
RPC URL: https://iotex-mainnet.gateway.pokt.network/v1/lb/6176f902e19001003499f492
Currency Symbol: IOTX
Block Explorer URL: https://iotexscan.io/

Second chain :

ChainID: 32520
Network Name: Bitgert
RPC URL: https://rpc.icecreamswap.com
Currency Symbol: BRISE
Block Explorer URL: https://brisescan.com

**Comment by mds1** [comment]
Both are now deployed, thanks!
