### ISSUE TITLE
MC3 Deployment on Kava

### ISSUE THREAD

**Issue by DefiDebauchery** [mds1/multicall#64]
Looking to add the static address to Kava - Chain ID 2222
RPC: https://evm2.kava.io

We've [funded](https://explorer.kava.io/tx/0x1dea275e87fbf92664706ebfa6a91f086625d6ae08aa28f3ca0c41b1fcd52e76/) the `0x05f32B3cC3888453ff71B01135B34FF8e41263F2` address with 0.2 KAVA for deployment costs.

Thank you!

**Comment by mds1** [comment]
Done, thanks! https://explorer.kava.io/address/0xcA11bde05977b3631167028862bE2a173976CA11/contracts
