### ISSUE TITLE
Deploy to Shardeum Sphinx Betanet

### ISSUE THREAD

**Issue by nfts2me** [mds1/multicall#66]
Requesting support for Multicall3 on Shardeum Sphinx Betanet. Can be found here:

Network Name: Shardeum Sphinx
New RPC URL: https://sphinx.shardeum.org/
Chain ID: 8082
Currency Symbol: SHM
Block Explorer URL: https://explorer-sphinx.shardeum.org/

https://docs.shardeum.org/network/endpoints

I can send you gas if needed.

**Comment by mds1** [comment]
If you could send funds to 0x05f32B3cC3888453ff71B01135B34FF8e41263F2 for deployment that would be great 🙂

**Comment by nfts2me** [comment]
> 0x05f32B3cC3888453ff71B01135B34FF8e41263F2

Sent!
It should be enough for several contracts deployment.
However, let me know if you need more.

**Comment by mds1** [comment]
Done, thanks! https://explorer-sphinx.shardeum.org/account/0xca11bde05977b3631167028862be2a173976ca11
