### ISSUE TITLE
Deploy Multicall3 to Coinbase Base L2 Testnet

### ISSUE THREAD

**Issue by robotoer** [mds1/multicall#69]
Requesting support for Multicall3 on Polygon zkEVM testnet. The block explorer can be found here:

ChainID: 84531
Network Name: Base Goerli
RPC URL: https://goerli.base.org/
Currency Symbol: ETH
Block Explorer URL: https://goerli.basescan.org/

There is a base goerli faucet here: https://coinbase.com/faucets/base-ethereum-goerli-faucet

**Comment by mds1** [comment]
Thanks, should be able to do this tomorrow or Monday. Alternatively, you can try deploying it yourself with this signed transaction: https://github.com/mds1/multicall/issues/68#issuecomment-1448772939

As mentioned in that comment, try it on a local fork first to make sure it deploys the expected code

**Comment by mds1** [comment]
Done https://goerli.basescan.org/address/0xca11bde05977b3631167028862be2a173976ca11#code

**Comment by robotoer** [comment]
Thank you!!
