### ISSUE TITLE
:rocket: Integrate Multicall3 with External Libraries

### ISSUE THREAD

**Issue by refcell** [mds1/multicall#7]
## Overview

Once deployed to the networks outlined in the [`README`](./README.md), `Multicall3` should be integrated into external libraries.

## Libraries

A list of external libraries that use existing `Multicall` or `Multicall2` contracts:
- [ ] https://github.com/snapshot-labs/snapshot.js
- [ ] https://github.com/makerdao/multicall.js
- [ ] https://github.com/0xsequence/sequence.js

**Comment by mds1** [comment]
Is this still worth keeping open?

**Comment by mds1** [comment]
Closing as Multicall is currently used by many tools:
- [wagmi](https://wagmi.sh/)
- [ethers-rs](https://github.com/gakonst/ethers-rs)
- [ethereum-multicall](https://github.com/joshstevens19/ethereum-multicall)
- [ethcall](https://github.com/Destiner/ethcall)
