### ISSUE TITLE
Deploy Multicall3 to DFK Chain

### ISSUE THREAD

**Issue by friskyfoxdk** [mds1/multicall#72]
Requesting support for Multicall3 on DFK Chain, Testnet and Mainnet. Here is the information for both chains:

Testnet:

ChainID: 335
Network Name: DFK Chain Test
RPC URL: https://subnets.avax.network/defi-kingdoms/dfk-chain-testnet/rpc
Currency Symbol: JEWEL
Block Explorer URL: https://subnets-test.avax.network/defi-kingdoms

Mainnet:

ChainID: 53935
Network Name: DFK Chain
RPC URL: https://subnets.avax.network/defi-kingdoms/dfk-chain/rpc
Currency Symbol: JEWEL
Block Explorer URL: https://subnets.avax.network/defi-kingdoms

---

I've sent 10 JEWEL to the deployer address on Mainnet and Testnet.

**Comment by mds1** [comment]
Done!
