### ISSUE TITLE
Please deploy multicall on Core Mainnet Blockchain 

### ISSUE THREAD

**Issue by Servegigab** [mds1/multicall#73]
Requesting support for Multicall3 on Coredao Blockchain Mainnet. The block explorer can be found here:

ChainID: 1116
Network Name: Core Blockchain
RPC URL: https://rpc.coredao.org/
Currency Symbol: CORE
Block Explorer URL: https://scan.coredao.org/

**Comment by mds1** [comment]
Can you send deployment funds to 0x05f32B3cC3888453ff71B01135B34FF8e41263F2? I have not used this chain so don't have any funds there
