### ISSUE TITLE
Deploy Multicall on Neon Devnet 

### ISSUE THREAD

**Issue by Sj-001** [mds1/multicall#74]
Requesting support for Multicall3 on Neon EVM DevNet. The block explorer can be found here:

ChainID: 245022926
Network Name: Neon EVM DevNet
RPC URL: https://devnet.neonevm.org
Currency Symbol: NEON
Block Explorer URL: https://neonscan.org/

@mds1

**Comment by mds1** [comment]
Can you send deployment funds to 0x05f32B3cC3888453ff71B01135B34FF8e41263F2? I have not used this chain so don't have any funds there

**Comment by Sj-001** [comment]
> 0x05f32B3cC3888453ff71B01135B34FF8e41263F2

@mds1 just sent 10 NEON to above address:)

**Comment by mds1** [comment]
Done, thanks! https://devnet.neonscan.org/address/0xcA11bde05977b3631167028862bE2a173976CA11#contract
