### ISSUE TITLE
Requesting support for Polygon zkEVM

### ISSUE THREAD

**Issue by agsola** [mds1/multicall#75]
Requesting support for Multicall3 on Polygon zkEVM. Can be found here:
Network Name: Polygon zkEVM
RPC URL: https://zkevm-rpc.com/
Chain ID: 1101
Currency Symbol: ETH
Block Explorer URL: https://zkevm.polygonscan.com/

https://wiki.polygon.technology/docs/zkEVM/develop/

**Comment by mds1** [comment]
Do you know if Polygon's zkEVM uses keccak / results in the same addresses as regular EVM chains? My understanding is that some zkEVM's use different hash functions which would mean we may not be able to deploy Multicall3 to those chains at the same address, and I'm not sure if polygon's is like that

**Comment by pcaversaccio** [comment]
Yes, please be careful with zkSync. I documented this here: https://twitter.com/pcaversaccio/status/1635346927465406465. Also, just for the record, Linear and Scroll zkEVMs are also safe to deploy to since they use the same RLP and keccak hashing for the CREATE tx.

**Comment by mds1** [comment]
Awesome, thank you both! @agsola I should be able to bridge some funds and deploy either tomorrow or Monday

**Comment by mds1** [comment]
If either of you know the answer to this question I just asked in their discord, let me know! The deployer account is funded on the Polygon zkEVM testnet and mainnet, just need to get it authorized, and haven't yet found how to do this in the docs

<img width="757" alt="image" src="https://user-images.githubusercontent.com/17163988/229625614-a4c2a797-31be-424c-b294-86ba172b14e5.png">

**Comment by mds1** [comment]
Deployed on polygon zkEVM mainnet and testnet!
