### ISSUE TITLE
Deploy multicall3 on zksync era

### ISSUE THREAD

**Issue by BisonFutil** [mds1/multicall#76]
Hi, could you please deploy multicall3 on zksync era. ETH has been transfer to the deployer account.

ChainID: 324
Network Name: zkSync Era
RPC URL:https://mainnet.era.zksync.io/
Currency Symbol: ETH
Block Explorer URL: https://explorer.zksync.io/

Thanks

**Comment by mds1** [comment]
My understanding is that it's not possible to deploy to the same address on zksync due to their design, as explained [here](https://twitter.com/pcaversaccio/status/1635346927465406465). However, it sounds like it will [eventually](https://twitter.com/gluk64/status/1635375609957474307) be possible, so I'm going to hold off on deploying on zkSync until that time. 

(Until then, you are of course free to deploy Multicall3 yourself to a different address)

**Comment by xalexec** [comment]
https://explorer.zksync.io/address/0x47898B2C52C957663aE9AB46922dCec150a2272c

**Comment by yura2100** [comment]
Also deployed it on zkSync Era Testnet
https://goerli.explorer.zksync.io/address/0x89e4EDbEC85362a285d7a1D5D255ccD2b8106be2

**Comment by mds1** [comment]
Thanks! Would either of you be willing to deploy to the other network also, i.e. so we can get the same address on both chains? I'm working on updating docs and will include these deployments, but figured it'd be nice for developers if we could get the same address on mainnet and testnet in the meantime

**Comment by xalexec** [comment]
sorry nonce already used,I deploy new
https://goerli.explorer.zksync.io/address/0xF9cda624FBC7e059355ce98a31693d299FACd963
https://explorer.zksync.io/address/0xF9cda624FBC7e059355ce98a31693d299FACd963

**Comment by mds1** [comment]
Really appreciate that, thanks so much @xalexec! 🙌

**Comment by mds1** [comment]
Closing this since it's now deployed on zksync era testnet and mainnet at the same address which is the best we can do for now. If/when zksync adds support for the same style deterministic deploys, we can redeploy at that time

**Comment by dutterbutter** [comment]
@xalexec do you think you can deploy to Sepolia as well :) https://github.com/mds1/multicall/issues/182

**Comment by xalexec** [comment]
> @xalexec do you think you can deploy to Sepolia as well :) #182

I can't find faucet in this testnet,plz give me some gas,I will try to deploy
0xaE0778D21949177Fc44B6Ccf07E5156015f9C58A

**Comment by dutterbutter** [comment]
@xalexec sent some, please let me know if you need more! Thank you!
