### ISSUE TITLE
Deploy multicall3 on HBIT Blockchain

### ISSUE THREAD

**Issue by HashBitorg** [mds1/multicall#78]
Anyone can do?

ChainID: 11119
https://explorer.hashbit.org
Coin: HBIT
RPC: https://rpc.hashbit.org

**Comment by mds1** [comment]
Are you able to fund the deployer account? I haven’t used this chain before, so that would help speed things up :)

**Comment by HashBitorg** [comment]
yes we do, just give the address and we send HBIT to deploy, we already deployed multicall and multicall2

**Comment by mds1** [comment]
Thanks! It's 0x05f32B3cC3888453ff71B01135B34FF8e41263F2. I should be able to do the deploy on sunday/monday

**Comment by HashBitorg** [comment]
https://explorer.hashbit.org/tx/0xa65bec53eeaecad6a9165fc91db69e59895b86c7044af34e6a3cc1ce744b504a

10 HBIT, you can deploy many contracts you want, just to know, we try to deploy multicall3, but return basefee error 32xxx
and i hope will be "0"
