### ISSUE TITLE
Deploy multicall3 to Syscoin networks

### ISSUE THREAD

**Issue by sidhujag** [mds1/multicall#79]
Can you please deploy multicall3 to our networks:

MAINNET:
ChainID: 57
https://explorer.syscoin.org/
Coin: SYS
RPC: https://rpc.syscoin.org/
Faucet: https://faucet.syscoin.org/
https://explorer.syscoin.org/tx/0xf3d14022f9f9eef61b2a790e924d6870ce53c512288cc2680b2ae95da8719d44

TESTNET:
ChainID: 5700
https://tanenbaum.io/
Coin: TSYS
RPC: https://rpc.tanenbaum.io/
Faucet: https://faucet.tanenbaum.io/
https://tanenbaum.io/tx/0xd0a711856868752c02373b16126faf697768f483106f88cd5268df96e2a84bc1

**Tanenbaum Rollux (our layer 2)**
ChainID: 57000
https://rollux.tanenbaum.io/
Coin: TSYS
RPC: https://rpc-tanenbaum.rollux.com
Faucet: https://sysdomains.xyz/rollux-faucet
https://rollux.tanenbaum.io/tx/0x81621e5f73e3ec92f6e69b735d8d5a14cac549404b80ba4a034bdb27b4b1f69e

Thank you!

**Comment by mds1** [comment]
Thanks, I should be able to do this early next week. I see the faucet links, but faucets can be flaky sometimes, so if you could fund the deployer account on each chain that would help speed things up :)

**Comment by sidhujag** [comment]
sent!

**Comment by mds1** [comment]
All deployed, thanks!
