### ISSUE TITLE
Deployment of MulticallV3 to Cronos 

### ISSUE THREAD

**Issue by simonjulianl** [mds1/multicall#8]
Link to block explorer: https://cronoscan.com/

**Comment by mds1** [comment]
Any chance you could send deployment funds to 0x05f32B3cC3888453ff71B01135B34FF8e41263F2? I have not used this chain, so it will take me some time to figure out how to get funds on it. I would guess that $10 of funds should be more than enough and I can refund the excess

**Comment by lauwsj-alpha** [comment]
Hi, Thank you so much for your help! Momentarily, I am not developing on this chain any longer, I will follow up in this issue and transfer some `CRO` in the future should the opportunities arise!

**Comment by mds1** [comment]
Deployed to Cronos: https://cronoscan.com/address/0xca11bde05977b3631167028862be2a173976ca11#code
