### ISSUE TITLE
Missing examples

### ISSUE THREAD

**Issue by liron-navon** [mds1/multicall#84]
There are no examples in the examples directory.

How do I call the multi call contract to read data if the "aggregate" function is payable?

**Comment by mds1** [comment]
Ah, yea they are almost done, you can find them in the examples directory on this branch: https://github.com/mds1/multicall/tree/chore/readme-and-examples

The answer depends on your language/libraries, so let me know if you can't find your answer there

**Comment by liron-navon** [comment]
Oh, this one works, thanks!

**Comment by mds1** [comment]
Closing since the README is now updated with docs/examples
