### ISSUE TITLE
Deploy multicall3 to Chain Verse network

### ISSUE THREAD

**Issue by stinkyandthebrain** [mds1/multicall#89]
### Chain Name

Chain Verse Mainnet

### Chain ID

5555(0x15b3)

### RPC URL

https://rpc.chainverse.info

### Block Explorer URL

https://explorer.chainverse.info/

### Deployment Funds

Yes

**Comment by stinkyandthebrain** [comment]
Chain Verse allows gasless deployment. The deployer address has been WL'ed. You can set gas to 0 (10e-19 or lower). Thanks for your serivce.

**Comment by mds1** [comment]
Done, thanks!
