### ISSUE TITLE
Deployment of MulticallV3 to Harmony

### ISSUE THREAD

**Issue by simonjulianl** [mds1/multicall#9]
Link to blockchain explorer: https://explorer.harmony.one/

**Comment by mds1** [comment]
Any chance you could send deployment funds to 0x05f32B3cC3888453ff71B01135B34FF8e41263F2? I have not used this chain, so it will take me some time to figure out how to get funds on it. I would guess that $10 of funds should be more than enough and I can refund the excess

**Comment by mds1** [comment]
Deployed! https://explorer.harmony.one/address/0xca11bde05977b3631167028862be2a173976ca11?activeTab=7

**Comment by lauwsj-alpha** [comment]
Hi, sorry for missing this update! Thank you very much for the deployment!
