### ISSUE TITLE
Deployment Request for Xodex network (zero-gas network)

### ISSUE THREAD

**Issue by goldnite** [mds1/multicall#96]
### Chain Name

Xodex

### Chain ID

2415

### RPC URL

https://mainnet.xo-dex.com/rpc

### Block Explorer URL

https://explorer.xo-dex.com

### Deployment Funds

No

**Comment by mds1** [comment]
Done, thanks! For posterity, just noting that Xodex is a zero-gas network so no deployment funds were needed: https://docs.xo-dex.com/docs/understanding-zero-gas
