### ISSUE TITLE
Filecoin Multicall deployment

### ISSUE THREAD

**Issue by odcey** [mds1/multicall#99]
### Chain Name

Filecoin

### Chain ID

314

### RPC URL

https://filecoin.chainup.net/rpc/v1

### Block Explorer URL

https://filfox.info/

### Deployment Funds

No

**Comment by tzapu** [comment]
this was done here https://github.com/mds1/multicall/issues/165 
cheers @mds1 🙇

**Comment by mds1** [comment]
Thanks, closing
